---
title: "Circular Economy"
author: "Mariësse van Sluisveld"
date: "5/27/2019"
output: html_document
---


# Testing environment

```{r results=TRUE, message=FALSE, warning=FALSE, echo=FALSE, fig.align="center", fig.width=11, fig.height=6, fig.cap="_**Figure**: A lot of ggnanimate_"}




# Clear memory
rm(list=ls()) # clear memory


#######################################################################################################################
### Install and/or load required packages / dependencies
#######################################################################################################################

# Easy scripting packages
if(!require(dplyr)){install.packages("dplyr");   library(dplyr)}
if(!require(forcats)){install.packages("forcats");  library(forcats)}
if(!require(data.table)){install.packages("data.table");  library(data.table)}
if(!require(tidyr)){install.packages("tidyr");  library(tidyr)}
if(!require(fuzzyjoin)){install.packages("fuzzyjoin");  library(fuzzyjoin)}
if(!require(stringr)){install.packages("stringr");  library(stringr)}
if(!require(rlang)){install.packages("rlang");  library(rlang)}

# text mining packages
if(!require(tidytext)){install.packages("tidytext");  library(tidytext)}
if(!require(tm)){install.packages("tm");  library(tm)}
if(!require(readxl)){install.packages("readxl");  library(readxl)}
if(!require(tabulizer)){install.packages("tabulizer");  library(tabulizer)}
if(!require(gtrendsR)){install.packages("gtrendsR");  library(gtrendsR)}
if(!require(trendyy)){install.packages("trendyy");  library(trendyy)}
if(!require(rtweet)){install.packages("rtweet");  library(rtweet)}


# data visualisation packages
if(!require(ggplot2)){install.packages("ggplot2");  library(ggplot2)}
if(!require(ggforce)){install.packages("ggforce");  library(ggforce)}
if(!require(plotly)){install.packages("plotly");  library(plotly)}
if(!require(paletteer)){install.packages("paletteer");  library(paletteer)}
if(!require(ggrepel)){install.packages("ggrepel");  library(ggrepel)}
if(!require(igraph)){install.packages("igraph");  library(igraph)}
if(!require(ggraph)){install.packages("ggraph");  library(ggraph)}
if(!require(ggforce)){install.packages("ggforce");  library(ggforce)}
if(!require(shadowtext)){install.packages("shadowtext");  library(shadowtext)}

# MyM cnversion packages
if(!require(mym2r)){install_github("marieyesse/mym2r");  library(mym2r)}

```

```{r results=TRUE, message=FALSE, warning=FALSE, echo=FALSE, fig.align="center", fig.width=11, fig.height=6, fig.cap="_**Figure**: A lot of ggnanimate_"}

# Trying trendyy

PBL_people <- c("PBL", "Planbureau voor de Leefomgeving", "Planbureau")


PBL_search <- trendy(PBL_people, from="2018-01-01", to="2019-05-27", geo=c("NL"))

PBL_search %>% 
  get_interest() %>% 
  ggplot(aes(date, hits, color = keyword)) +
  geom_line() +
  geom_point(alpha = .2) +
  theme_minimal()  +
  ggsave(paste("Google_trend_search_PBL",".png", sep=""), width = 8, height = 5, units = c("in"), dpi=200) 



PBL_search %>%  
  get_related_topics() %>% 
  group_by(keyword)

```
