---
title: "gganimate"
output: html_document
---

# Testing environment

```{r results=TRUE, message=FALSE, warning=FALSE, echo=FALSE, fig.align="center", fig.width=11, fig.height=6, fig.cap="_**Figure**: A lot of ggnanimate_"}



# install.packages('devtools')
devtools::install_github('bbc/bbplot')
library(bbplot)


library(plotly)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(forcats)

library(gganimate)
library(gifski)
library(glue)


# IMAGE

ALLVAR=read.csv("data/Compilation_IMAGE_REINENT_everything.csv", sep=";", dec=".")
ALLVAR=data.table(ALLVAR)

FINE = ALLVAR[Variable %in% c(
        "Final Energy|Industry|Iron and Steel|Coal",
      "Final Energy|Industry|Iron and Steel|Electricity",
      "Final Energy|Industry|Iron and Steel|Gaseous Fuel",
      "Final Energy|Industry|Iron and Steel|Hydrogen",
      "Final Energy|Industry|Iron and Steel|Liquid Fuel",
      "Final Energy|Industry|Iron and Steel|Modern Biofuel",
      "Final Energy|Industry|Iron and Steel|Secondary Heat",
      "Final Energy|Industry|Iron and Steel|Traditional Biofuel",
      "Final Energy|Industry|Pulp and Paper|Coal",
      "Final Energy|Industry|Pulp and Paper|Electricity",
      "Final Energy|Industry|Pulp and Paper|Gaseous Fuel",
      "Final Energy|Industry|Pulp and Paper|Hydrogen",
      "Final Energy|Industry|Pulp and Paper|Liquid Fuel",
      "Final Energy|Industry|Pulp and Paper|Modern Biofuel",
      "Final Energy|Industry|Pulp and Paper|Secondary Heat",
      "Final Energy|Industry|Pulp and Paper|Thermal",
      "Final Energy|Industry|Pulp and Paper|Traditional Biofuel",
      "Final Energy|Industry|Food Processing|Coal",
      "Final Energy|Industry|Food Processing|Electricity",
      "Final Energy|Industry|Food Processing|Gaseous Fuel",
      "Final Energy|Industry|Food Processing|Hydrogen",
      "Final Energy|Industry|Food Processing|Liquid Fuel",
      "Final Energy|Industry|Food Processing|Modern Biofuel",
      "Final Energy|Industry|Food Processing|Secondary Heat",
      "Final Energy|Industry|Food Processing|Traditional Biofuel",
      "Final Energy|Industry|Chemicals and Petrochemicals|Coal",
      "Final Energy|Industry|Chemicals and Petrochemicals|Electricity",
      "Final Energy|Industry|Chemicals and Petrochemicals|Gaseous Fuel",
      "Final Energy|Industry|Chemicals and Petrochemicals|Liquid Fuel",
      "Final Energy|Industry|Chemicals and Petrochemicals|Modern Biofuel"

      )]

FINEsplit<- data.frame(do.call('rbind', strsplit(as.character(FINE$Variable),'|',fixed=TRUE)))
FINE=cbind(FINE,FINEsplit$X1,FINEsplit$X3, FINEsplit$X4)
FINE$Variable <- NULL
setnames(FINE, "V2", "Indicator")
setnames(FINE, "V3", "Sector")
setnames(FINE, "V4", "Carrier")

FINE$label <-paste(FINE$Carrier, FINE$Scenario)
FINE=FINE[Sector=="Chemicals and Petrochemicals", Sector:=c("Chemicals")]
FINEanim = ggplot()+
  geom_bar(data=FINE[Region=="EU28" & Year %in% c(2010:2100)], aes(x=Scenario, y=value, fill=Carrier), colour='black', position="stack", stat="identity") +
  facet_wrap(~Sector, nrow=1) +
  xlab("industry")+ ylab("EJ/yr") +
 theme_bw() +
  geom_label(data=FINE[Region=="EU28" & Year %in% c(2010:2100)], aes(x=Scenario, y=value, label=substr(Carrier,1,2), group=label, fill=Carrier), size=2.5, colour="black",  position=position_stack(vjust=0.5)) +
  scale_fill_manual(values=c('#a50026','#d73027','#f46d43','#fdae61','#fee090','#2ca25f','#abd9e9','#74add1','#4575b4','#313695'))+
#  bbc_style()+
   theme(
        axis.text.x = element_text(angle = 45, size=12,  hjust=1),
        axis.title.y = element_text(size=13),
        axis.title.x = element_text(size=13),
        axis.text.y = element_text(size=12),
        strip.text.x = element_text(size=12, face="bold"),
        strip.text.y = element_text(size=12, face="bold"),
        legend.text= element_text(size=12),
        legend.title=element_text(size=13,  face="bold"),
        plot.title=element_text(size=16, hjust=0.5, face="bold"), 
        plot.subtitle=element_text(size=14,hjust=0.5),
        panel.border = element_rect(colour = "black", size=1),
        legend.key =  element_rect(fill = 'white', size = 0.5),
        strip.background = element_rect(colour="white", fill="#FFFFFF")
    ) 



FINEanim = FINEanim +
         transition_components(Year) +
      exit_reset() +
       labs(title = 'Year: {substr(frame_time, 1,4)} \n Final Energy Use per Carrier')

  FINEanim
```
  
  
```{r results=TRUE, message=FALSE, warning=FALSE, echo=FALSE, fig.align="center", fig.width=8, fig.height=4, fig.cap="_**Figure**: A lot of ggnanimate_"}


CEMIS <- function(df, startyear, endyear){
 
  df.intrapolate=seq(unique(df$Year)[1],endyear) 
  
  ## Activate data.table package ###
  dfreal=data.table(df)
  
  #Intrapolatie with approximate
  dfreal = dfreal[,list(approx(x=Year,y=value,xout=df.intrapolate)$y,
                        approx(x=Year,y=value,xout=df.intrapolate)$x),
                             by=eval(dput(names(dfreal[, -c("Year", "value")])))]
  
  setnames(dfreal,"V1","value")
  setnames(dfreal,"V2","Year")
  
  dfreal=data.table(dfreal)
 
  df = dfreal[Year %in% c(startyear:endyear)] %>% 
    group_by_at(names(dfreal[, -c("Year", "value")])) %>% 
    mutate(CEMIS=cumsum(value)) 
  
  df = data.table(df)
  
}

CumEMIS <- CEMIS(ALLVAR, 2018, 2100)


CumEMIS=CumEMIS[Variable %in% c( "Emissions|CO2|Fossil Fuels and Industry|Energy Demand|Industry",
                                        "Emissions|CO2|Iron and Steel|Direct emissions",
                                        "Emissions|CO2|Pulp and Paper|Direct emissions",
                                        "Emissions|CO2|Chemicals and Petrochemicals|Direct emissions",
                                        "Emissions|CO2|Food Processing|Direct emissions",
                                        "Emissions|CO2|Cement|Direct emissions",
                                        "Emissions|CO2|Carbon Capture and Storage|Biomass|Energy|Supply|Electricity",
                                        "Emissions|CO2|Carbon Capture and Storage|Biomass|Energy|Demand|Industry", 
                                        "Emissions|CO2|Carbon Capture and Storage|Fossil|Energy|Supply|Electricity",
                                        "Emissions|CO2|Carbon Capture and Storage|Fossil|Energy|Demand|Industry", 
                                        "Emissions|CO2|Carbon Capture and Storage|Biomass|Industrial Processes|Pulp and Paper",
                                        "Emissions|CO2|Carbon Capture and Storage|Fossil|Industrial Processes|Pulp and Paper",
                                        "Emissions|CO2|Carbon Capture and Storage|Biomass|Industrial Processes|Iron and Steel",
                                        "Emissions|CO2|Carbon Capture and Storage|Fossil|Industrial Processes|Iron and Steel"
                                                           )]

CumEMIS$Variable <- gsub("Emissions|CO2|Fossil Fuels and Industry|Energy Demand|", "", CumEMIS$Variable, fixed=T )
CumEMIS$Variable <- gsub("|Direct emissions", "", CumEMIS$Variable, fixed=T )
CumEMIS$Variable <- gsub("Emissions|CO2|", "", CumEMIS$Variable, fixed=T )
CumEMIS$Variable <- gsub("Emissions|CO2|Carbon Capture and Storage|", "", CumEMIS$Variable, fixed=TRUE)
CumEMIS$Variable <- gsub("Carbon Capture and Storage|", "", CumEMIS$Variable, fixed=TRUE)
CumEMIS$Variable <- gsub("|Energy|Demand", "", CumEMIS$Variable, fixed=TRUE)
CumEMIS$Variable <- gsub("Industrial Processes|", "", CumEMIS$Variable, fixed=TRUE)

CumEMIS=data.table(CumEMIS)

CEMISanim=ggplot()+
  geom_bar(data=CumEMIS[Variable %in% c("Industry") & Region %in% c("EU28")], aes(x=Scenario, y=CEMIS/1000), fill=' grey80' ,  position="stack", stat="identity") +
   geom_bar(data=CumEMIS[Variable %in% c("Biomass|Industry") & Region %in% c("EU28")], aes(x=Scenario, y=-CEMIS/1000, fill=Variable), stat="identity", position="stack")+
     geom_bar(data=CumEMIS[Variable %in% c("Iron and Steel", "Chemicals and Petrochemicals",  "Cement", "Food Processing")  & Region %in% c("EU28")], aes(x=Scenario, y=CEMIS/1000, fill=Variable), stat="identity", position="stack")+
  xlab(" Scenario") + ylab(bquote("Gt")) +
coord_flip()+
    theme_bw() +

  theme(
        axis.text.x = element_text(angle = 45, size=12,  hjust=1),
        axis.title.y = element_text(size=13),
        axis.title.x = element_text(size=13),
        axis.text.y = element_text(size=12),
        strip.text.x = element_text(size=12, face="bold"),
        strip.text.y = element_text(size=12, face="bold"),
        legend.text= element_text(size=12),
        legend.title=element_text(size=13,  face="bold"),
        plot.title=element_text(size=16, hjust=0.5, face="bold"), 
        plot.subtitle=element_text(size=14,hjust=0.5),
        panel.border = element_rect(colour = "black", size=1),
        legend.key =  element_rect(fill = 'white', size = 0.5),
        strip.background = element_rect(colour="white", fill="#FFFFFF")
    ) 

#print(CEMISanim)

  
  
CEMISanim <-  CEMISanim +  transition_time(Year) +
      exit_reset() +
         labs(title = 'Year: {substr(frame_time, 1,4)} \n Cumulative CO2 emissions')
  
CEMISanim

  
print(CEMISanim)



```



```{r results=TRUE, message=FALSE, warning=FALSE, echo=FALSE, fig.align="center", fig.width=8, fig.height=7, fig.cap="_**Figure**: A lot of ggnanimate_"}



# install.packages('devtools')
devtools::install_github('bbc/bbplot')
library(bbplot)


library(plotly)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(forcats)

library(gganimate)
library(gifski)
library(glue)

ALLSRES15 = read.csv("data/iamc15_snapshot_1549066125_world.csv", sep=",", dec=".")

SUBSETTING= read.csv("data/iamc15_snapshot_1549297260_Glob_med_temp.csv", sep=",", dec=".")
SUBSETTING=data.table(SUBSETTING)

#FFS
SS15=SUBSETTING[X2100 < 1.5]
SS15$IPCC<- '1.5C or below'
SS2=SUBSETTING[X2100 >=1.5 & X2100 <= 2.0]   
SS2$IPCC <- 'Below 2C'
SSx=SUBSETTING[X2100 > 2.0]
SSx$IPCC <- 'Beyond Paris'

SUBSET=rbind(SS15, SS2, SSx)
SUBSET=SUBSET[, c("Model", "Scenario", "Region", "IPCC")]

ALLSRES15=melt(ALLSRES15,  id.vars=c("Model","Scenario","Region","Variable", "Unit"), variable.name="Year")
ALLSRES15$Year = as.numeric(as.character(substr(ALLSRES15$Year, 2, stop=100)))

ALLSRES15=merge(ALLSRES15, SUBSET, by=c("Model", "Scenario", "Region"))

CEMIS <- function(df, startyear, endyear){
 
  df.intrapolate=seq(unique(df$Year)[1],endyear) 
  
  ## Activate data.table package ###
  dfreal=data.table(df)
  
  #Intrapolatie with approximate
  dfreal = dfreal[,list(approx(x=Year,y=value,xout=df.intrapolate)$y,
                        approx(x=Year,y=value,xout=df.intrapolate)$x),
                             by=eval(dput(names(dfreal[, -c("Year", "value")])))]
  
  setnames(dfreal,"V1","value")
  setnames(dfreal,"V2","Year")
  
  dfreal=data.table(dfreal)
 
  df = dfreal[Year %in% c(startyear:endyear)] %>% 
    group_by_at(names(dfreal[, -c("Year", "value")])) %>% 
    mutate(CEMIS=cumsum(value)) 
  
  df = data.table(df)
  
}

ALLSRES15 <- na.omit(ALLSRES15)
ALLSRES15cum <- CEMIS(ALLSRES15, 2010, 2100)
ALLSRES15cumdelta = ALLSRES15cum %>% 
                    mutate(Delta = CEMIS-lag(CEMIS)) %>%
                    mutate(Delta = if_else(is.na(Delta), 0, Delta))

ALLSRES15cumdelta=data.table(ALLSRES15cumdelta)
CALCALLRES15=spread(ALLSRES15cumdelta[, -c("Delta", "Unit", "CEMIS")], Variable, value)

CALCALLRES15 = CALCALLRES15 %>% 
                    rename('CO2'='Emissions|CO2',
                           'MER' ='GDP|MER',
                           'PPP' = 'GDP|PPP',
                           'PRIME'='Primary Energy') %>%
                    mutate(EI=(PRIME/MER)*1000,  EE=CO2/PRIME)

DECARBplot = ggplot() +
    geom_point(data=CALCALLRES15, aes(x=EI, y=EE, colour=IPCC), size=2, alpha=0.6) +
          theme_bw() +
    guides(fill=guide_legend( title="Model",ncol=1 )) +
xlab('Energy Efficiency (GJ/$gdp)') + ylab('Decarbonization (kg CO2/GJ)') +
  theme(
        axis.text.x = element_text(angle = 45, size=12,  hjust=1),
        axis.title.y = element_text(size=13),
        axis.title.x = element_text(size=13),
        axis.text.y = element_text(size=12),
        strip.text.x = element_text(size=12, face="bold"),
        strip.text.y = element_text(size=12, face="bold"),
        legend.text= element_text(size=12),
        legend.title=element_text(size=13,  face="bold"),
        plot.title=element_text(size=16, hjust=0.5, face="bold"), 
        plot.subtitle=element_text(size=14,hjust=0.5),
        panel.border = element_rect(colour = "black", size=1),
        legend.key =  element_rect(fill = 'white', size = 0.5),
        strip.background = element_rect(colour="white", fill="#FFFFFF")
    ) +
  scale_colour_manual(values=c('#91cf60','#fdae61','#d7191c'))
    
# print(DECARBplot)

    
    DECARBplot <- DECARBplot + transition_time(Year) +
            labs(title = 'Year: {substr(frame_time, 1,4)} \n Decarbonization strategies')
    
    DECARBplot
    
```



