---
title: "Research"
---

### [Data study: REINVENT meta-data overview](reinvent_meta.html)

> In this page I sort out the information from the [REINVENT project](https://www.reinvent-project.eu), analysing the object of study from a higher meta level. I show a mapping of roadmap/scenario studies to different classifications, a word network analysis, and do the same thing for the [REINVENT Innovations DB](https://zenodo.org/record/1284945#.XIwmhdpKiUn).


### [Data study: What have the IEA World Energy Outlooks been saying about industry? ](WEO_Industry.html)

> I had a little curiosity about the change of outcome of IEA-WEM scenarios with progressing knowledge and time  - hence I have extracted all the data of all World Energy Outlooks from 2014 till now for all the common indicators (aggregated for the sector as a whole). Only the 2018 publication has detail on basic industries, did you know that? 

### [Data study: Analysing Industry Trade and Business Associations](twitter_talk.html)

> In this page I sort out the information from the [EU Transparancy Register](http://ec.europa.eu/transparencyregister/public/consultation/search.do?locale=en&reset=) for the [REINVENT](http://www.reinvent-project.eu) industry sectors to get an idea about the role of business and trade associations. Subsequently, I have ran some twittercrawl scripts over the CEFIC, PlasticsEurope, CEMBUREAU, EUROFER_EU, CEPI_Paper, EDA_Dairy and FIL_IDF twitter timelines to see what their current points of discussion are. 

### [Data study: Comparing model to expert projections](tech_survey.html)

> To test whether projections by IAMs diverge in systematic ways from projections made by technology experts we elicited expert opinion on prospective change for two indicators and compared these with the outcomes of IAM studies. We focused on solar, wind, biomass, nuclear, and carbon capture and storage or CCS technologies for the short (2030) to medium (2050) term.

### [Data study: European industry decarbonisation Strategies](IAM_dashboard.html)

> On this page I look at the change in industrial energy productivity (energy unit per value added) and industrial emissions intensity (emissions per unit of energy used). In the data I compare both the decades’ average annual reduction rate [linear rate] and the decades’ compound average annual reduction rate [exponential reduction]. Full report: [REINVENT Deliverable 4.1](https://static1.squarespace.com/static/59f0cb986957da5faf64971e/t/5a968cd7652deaeda0a2a62a/1519815901936/D4.1+Existing+visions+and+scenarios.pdf)

###  [Interactive Poster: Industry decarbonisation towards 2050](industry.html) 

> On this page I present the data used on an earlier published poster on industry decarbonisation by 2050 according to the global model [IMAGE](http://www.twitter.com/IMAGE_PBL) and the bottom-up energy model [WISEE](www.wuppertal.org/us). The page is a republication of [REINVENT deliverable 4.2](https://static1.squarespace.com/static/59f0cb986957da5faf64971e/t/5b3fdf266d2a73e319355e0c/1530912585721/D4.2+EU+decarbonisation+scenarios+for+industry.pdf)

