---
title: "Twitter reads"
---
```{r results=TRUE, message=FALSE, warning=FALSE, echo=FALSE}

library(plotly)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(gridExtra)

```

I am a twitter enthusiast - mostly using my account for work related things. Messages that are closely related to what I am working on will be retweeted, and tweets considered relevant but not on my priority list are liked. Here I structure some of my favorites to the topics that catch my interest.

# 2019

## Materials / Resources

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Explainer: These six metals are key to a low-carbon future | <a href="https://twitter.com/jloistf?ref_src=twsrc%5Etfw">@jloistf</a> <a href="https://t.co/As2Zgl6sFv">https://t.co/As2Zgl6sFv</a> <a href="https://twitter.com/hashtag/archive?src=hash&amp;ref_src=twsrc%5Etfw">#archive</a> <a href="https://t.co/Jg70rdJePe">pic.twitter.com/Jg70rdJePe</a></p>&mdash; Carbon Brief (@CarbonBrief) <a href="https://twitter.com/CarbonBrief/status/1089576519880429568?ref_src=twsrc%5Etfw">27 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Transition indicators

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Looking for EU energy &amp; climate statistics? <a href="https://twitter.com/hashtag/EurStatsDay?src=hash&amp;ref_src=twsrc%5Etfw">#EurStatsDay</a> <br>The <a href="https://twitter.com/hashtag/EnergyUnion?src=hash&amp;ref_src=twsrc%5Etfw">#EnergyUnion</a> indicators web tool offers you the possibility to check &amp; download the main energy &amp; climate indicators on scoreboards, maps, graphs &amp; tables: <a href="https://t.co/tdlnGJVrHQ">https://t.co/tdlnGJVrHQ</a> <a href="https://t.co/zlGX07ESj6">pic.twitter.com/zlGX07ESj6</a></p>&mdash; Energy4Europe 🇪🇺 (@Energy4Europe) <a href="https://twitter.com/Energy4Europe/status/1053345039806533633?ref_src=twsrc%5Etfw">19 oktober 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## R tricks / Methods

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Just built my first <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> package for internal company use. Why didn&#39;t I start doing this sooner? Takes approximately 1 hour to put a few functions in a package that all can share.<br><br>Thanks to <a href="https://twitter.com/hspter?ref_src=twsrc%5Etfw">@hspter</a> for the guide: <a href="https://t.co/vAavmvnA5o">https://t.co/vAavmvnA5o</a></p>&mdash; Evan Kaeding (@EvanKaeding) <a href="https://twitter.com/EvanKaeding/status/1100196463634608128?ref_src=twsrc%5Etfw">26 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Learning Data Science: Modelling Basics <a href="https://t.co/lfbVofdxIZ">https://t.co/lfbVofdxIZ</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a></p>&mdash; R-bloggers (@Rbloggers) <a href="https://twitter.com/Rbloggers/status/1092801342047956993?ref_src=twsrc%5Etfw">5 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">100+ Free <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> Books — covers <a href="https://twitter.com/hashtag/BigData?src=hash&amp;ref_src=twsrc%5Etfw">#BigData</a>, <a href="https://twitter.com/hashtag/DataMining?src=hash&amp;ref_src=twsrc%5Etfw">#DataMining</a>, <a href="https://twitter.com/hashtag/MachineLearning?src=hash&amp;ref_src=twsrc%5Etfw">#MachineLearning</a>, <a href="https://twitter.com/hashtag/AI?src=hash&amp;ref_src=twsrc%5Etfw">#AI</a>, <a href="https://twitter.com/hashtag/Python?src=hash&amp;ref_src=twsrc%5Etfw">#Python</a>, R, SQL, NoSQL and more: <a href="https://t.co/rF1pdtUxhm">https://t.co/rF1pdtUxhm</a> <a href="https://twitter.com/hashtag/Rstats?src=hash&amp;ref_src=twsrc%5Etfw">#Rstats</a> <a href="https://twitter.com/hashtag/Coding?src=hash&amp;ref_src=twsrc%5Etfw">#Coding</a> <a href="https://twitter.com/hashtag/DataScientists?src=hash&amp;ref_src=twsrc%5Etfw">#DataScientists</a> <br>HT <a href="https://twitter.com/nitinramrap?ref_src=twsrc%5Etfw">@nitinramrap</a> <a href="https://t.co/xbu6oz2QGo">pic.twitter.com/xbu6oz2QGo</a></p>&mdash; Kirk Borne (@KirkDBorne) <a href="https://twitter.com/KirkDBorne/status/1092635580742144000?ref_src=twsrc%5Etfw">5 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Here&#39;s my rough thoughts about multi-gather() and multi-spread(). Hope this contributes to the discussions about tidy data... <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a><br><br>Enhancing gather() and spread() by Using &quot;Bundled&quot; data.frames | Wannabe Rstats-fu <a href="https://t.co/ErPZHVO7Gb">https://t.co/ErPZHVO7Gb</a> <a href="https://t.co/pRUgaRQC6U">pic.twitter.com/pRUgaRQC6U</a></p>&mdash; Hiroaki Yutani (@yutannihilat_en) <a href="https://twitter.com/yutannihilat_en/status/1091971991500840960?ref_src=twsrc%5Etfw">3 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Tools / Practices

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">11Officially a contributor to broom (<a href="https://t.co/FzNYgDsTDi">https://t.co/FzNYgDsTDi</a>)! Massive kudos to <a href="https://twitter.com/alexpghayes?ref_src=twsrc%5Etfw">@alexpghayes</a> for guiding us through this <a href="https://twitter.com/hashtag/chirunconf?src=hash&amp;ref_src=twsrc%5Etfw">#chirunconf</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; Wei Yang Tham🔎 (@wytham88) <a href="https://twitter.com/wytham88/status/1104498035168559114?ref_src=twsrc%5Etfw">9 maart 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">5 links (so far) to tipsheets, tools, presentations and data sources from the <a href="https://twitter.com/hashtag/NICAR19?src=hash&amp;ref_src=twsrc%5Etfw">#NICAR19</a> data journalism conference: <a href="https://t.co/J2WymrrOU9">https://t.co/J2WymrrOU9</a> <a href="https://t.co/3aGWZqhz3n">pic.twitter.com/3aGWZqhz3n</a></p>&mdash; Sharon Machlis (@sharon000) <a href="https://twitter.com/sharon000/status/1104225780719149056?ref_src=twsrc%5Etfw">9 maart 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Tidyverse style guide (<a href="https://t.co/Hrel7FdgkH">https://t.co/Hrel7FdgkH</a>) now has PDF (<a href="https://t.co/extmejTDNd">https://t.co/extmejTDNd</a>) and EPUB (<a href="https://t.co/YDncMo2k8I">https://t.co/YDncMo2k8I</a>) versions for your reading pleasure <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; Hadley Wickham (@hadleywickham) <a href="https://twitter.com/hadleywickham/status/1091774173758795776?ref_src=twsrc%5Etfw">2 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🍿 Siri, cancel my weekend plans…<br>🎥 &quot;rstudio::conf 2019&quot; <a href="https://t.co/At0vxZUFCi">https://t.co/At0vxZUFCi</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> <a href="https://t.co/Z8KBltZKN7">pic.twitter.com/Z8KBltZKN7</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1088794504101089281?ref_src=twsrc%5Etfw">25 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Hadn’t seen this one. Great little introduction to the patchwork API <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/EYELffQZtj">https://t.co/EYELffQZtj</a></p>&mdash; Thomas Lin Pedersen (@thomasp85) <a href="https://twitter.com/thomasp85/status/1089101258286354433?ref_src=twsrc%5Etfw">26 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">If you are interested in getting started with building animations with gganimate, my <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> talk, going through 3 different examples, is now online <a href="https://t.co/SfYa2VX0Ni">https://t.co/SfYa2VX0Ni</a></p>&mdash; Thomas Lin Pedersen (@thomasp85) <a href="https://twitter.com/thomasp85/status/1088777792748175361?ref_src=twsrc%5Etfw">25 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Writing / comms

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Inspired by <a href="https://twitter.com/xieyihui?ref_src=twsrc%5Etfw">@xieyihui</a>&#39;s <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> talk I&#39;ve added the ability to knit 🧶 conference posters using posterdown 📦 to an <a href="https://twitter.com/hashtag/html?src=hash&amp;ref_src=twsrc%5Etfw">#html</a> document! The best part is that you can use packages like <a href="https://twitter.com/thomasp85?ref_src=twsrc%5Etfw">@thomasp85</a> &#39;s <a href="https://twitter.com/hashtag/gganimate?src=hash&amp;ref_src=twsrc%5Etfw">#gganimate</a> / <a href="https://twitter.com/hashtag/leaflet?src=hash&amp;ref_src=twsrc%5Etfw">#leaflet</a> to expand the <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> fun! <a href="https://t.co/UsW4crrPZO">https://t.co/UsW4crrPZO</a> <a href="https://t.co/MA74kup67s">pic.twitter.com/MA74kup67s</a></p>&mdash; Brent Thorne (@brentthorne18) <a href="https://twitter.com/brentthorne18/status/1093344160042618881?ref_src=twsrc%5Etfw">7 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Software authors deserve being cited too! <br>For <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a>, just run `grateful::cite_packages()` and get citations ready to paste into your manuscript!<a href="https://t.co/m2RlAryQUS">https://t.co/m2RlAryQUS</a> <a href="https://t.co/Srxic8avIQ">https://t.co/Srxic8avIQ</a></p>&mdash; F Rodriguez-Sanchez (@frod_san) <a href="https://twitter.com/frod_san/status/1093234220787474435?ref_src=twsrc%5Etfw">6 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## (Data) Visualisation
<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🤯 Welp, <a href="https://twitter.com/Datatitian?ref_src=twsrc%5Etfw">@Datatitian</a> just blew my mind (it even works in link preview)!<br>&quot;How to Turn Your ggplot2 Visualization into an Interactive Tweet&quot;  <a href="https://t.co/MArL4PPBYJ">https://t.co/MArL4PPBYJ</a> ht <a href="https://twitter.com/blaine_bateman?ref_src=twsrc%5Etfw">@blaine_bateman</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://t.co/MzTlXz0to6">pic.twitter.com/MzTlXz0to6</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1101995679981944832?ref_src=twsrc%5Etfw">3 maart 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🎉 paletteer version 0.2.1 hit CRAN!<br>With the addition of palettes from 3 more packages we got past 1000 palettes 😮 <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a><a href="https://t.co/XKUNqwdvOZ">https://t.co/XKUNqwdvOZ</a> <a href="https://t.co/8XsIypQMEG">pic.twitter.com/8XsIypQMEG</a></p>&mdash; Emil Hvitfeldt (@Emil_Hvitfeldt) <a href="https://twitter.com/Emil_Hvitfeldt/status/1095915915491725312?ref_src=twsrc%5Etfw">14 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">I became the one of the maintainers of <a href="https://twitter.com/hashtag/ggplot2?src=hash&amp;ref_src=twsrc%5Etfw">#ggplot2</a>-exts, a nice showcase of ggplot2 extension packages📦 by <a href="https://twitter.com/Emaasit?ref_src=twsrc%5Etfw">@emaasit</a>. If you notice some must-know extension is not listed here, please send us a PR! <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a><br><br>Gallery: <a href="https://t.co/BMl5U7jbor">https://t.co/BMl5U7jbor</a><br>repo: <a href="https://t.co/8qrfXVTNmm">https://t.co/8qrfXVTNmm</a> <a href="https://t.co/D4aSGlcol4">pic.twitter.com/D4aSGlcol4</a></p>&mdash; Hiroaki Yutani (@yutannihilat_en) <a href="https://twitter.com/yutannihilat_en/status/1094840337569181696?ref_src=twsrc%5Etfw">11 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">The first public release of the isoband 📦 is now on CRAN.<a href="https://t.co/dLswXjQubx">https://t.co/dLswXjQubx</a> <a href="https://t.co/3mt7C0YxTg">pic.twitter.com/3mt7C0YxTg</a></p>&mdash; Claus Wilke (@ClausWilke) <a href="https://twitter.com/ClausWilke/status/1092097173150408706?ref_src=twsrc%5Etfw">3 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">I&#39;m in a little over my head on this one, but this looked really cool so I cooked up a script for anyone looking to make horrifying versions of their faces too: <a href="https://t.co/IRCEXb8NLk">https://t.co/IRCEXb8NLk</a></p>&mdash; Rich Abdill (@richabdill) <a href="https://twitter.com/richabdill/status/1089027443351060487?ref_src=twsrc%5Etfw">26 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Maps / Spatial Data visualization

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">😻 A treasure trove of resources by <a href="https://twitter.com/spatialanalysis?ref_src=twsrc%5Etfw">@spatialanalysis</a><br>🗺 &quot;Maps and Data Visualisations with R&quot; <a href="https://t.co/Vn3fr2Yqor">https://t.co/Vn3fr2Yqor</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://twitter.com/hashtag/rspatial?src=hash&amp;ref_src=twsrc%5Etfw">#rspatial</a> <a href="https://t.co/7unGBFAYYh">pic.twitter.com/7unGBFAYYh</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1101905522557702145?ref_src=twsrc%5Etfw">2 maart 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🗺 A tour through some R map-making 📦s...<br>&quot;Introduction to mapping with {sf} &amp; co.&quot;  📐 <a href="https://twitter.com/StatnMap?ref_src=twsrc%5Etfw">@StatnMap</a> <a href="https://t.co/DOTYUedX62">https://t.co/DOTYUedX62</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/maps?src=hash&amp;ref_src=twsrc%5Etfw">#maps</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a><a href="https://twitter.com/hashtag/repeatTweet?src=hash&amp;ref_src=twsrc%5Etfw">#repeatTweet</a> <a href="https://t.co/Y6JUZORLMe">pic.twitter.com/Y6JUZORLMe</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1089359600384688128?ref_src=twsrc%5Etfw">27 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🌎  Great code-through:<br>&quot;Intro to GIS w/ R: spatial data w/ the sp &amp; sf packages&quot; ✏️ <a href="https://twitter.com/vivalosburros?ref_src=twsrc%5Etfw">@vivalosburros</a><a href="https://t.co/abHNU1qCza">https://t.co/abHNU1qCza</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/rspatial?src=hash&amp;ref_src=twsrc%5Etfw">#rspatial</a> <a href="https://twitter.com/hashtag/repeatTweet?src=hash&amp;ref_src=twsrc%5Etfw">#repeatTweet</a> <a href="https://t.co/QEuImc0wRY">pic.twitter.com/QEuImc0wRY</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1090010893327450112?ref_src=twsrc%5Etfw">28 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


##  Webscraping and API's

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Lecture 7: Webscraping: (2) Client-side and APIs. <a href="https://t.co/eeAc7dezbW">https://t.co/eeAc7dezbW</a><br><br>Including an eccentric mix of applications from NYC trees... to US GNP data... to World Rugby rankings (most importantly obvs). <a href="https://t.co/8D4V2xGXLP">pic.twitter.com/8D4V2xGXLP</a></p>&mdash; Grant McDermott (@grant_mcdermott) <a href="https://twitter.com/grant_mcdermott/status/1091139456180973568?ref_src=twsrc%5Etfw">1 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Useless but funny

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">i like to use the beepr package to make it sound like finished a level on Super Mario every time I run a line of code</p>&mdash; Matt Crayne (@mattcrayne) <a href="https://twitter.com/mattcrayne/status/1100924286385209344?ref_src=twsrc%5Etfw">28 februari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


# 2018

## Model Evaluation

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New paper in <a href="https://twitter.com/NatureComms?ref_src=twsrc%5Etfw">@NatureComms</a> about the practice and perspectives in model validation <a href="https://t.co/m8Psqhgb1o">https://t.co/m8Psqhgb1o</a> <a href="https://t.co/V5qzoqo3OP">pic.twitter.com/V5qzoqo3OP</a></p>&mdash; Sibel Eker (@sibel_eker_) <a href="https://twitter.com/sibel_eker_/status/1075007399537324033?ref_src=twsrc%5Etfw">18 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Interesting read: Insights on <a href="https://twitter.com/hashtag/IAM?src=hash&amp;ref_src=twsrc%5Etfw">#IAM</a> <a href="https://twitter.com/hashtag/Evaluation?src=hash&amp;ref_src=twsrc%5Etfw">#Evaluation</a> by Charlie Wilson <a href="https://twitter.com/DetlefvanVuuren?ref_src=twsrc%5Etfw">@DetlefvanVuuren</a> <a href="https://twitter.com/CelineGuivarch?ref_src=twsrc%5Etfw">@CelineGuivarch</a> et al <a href="https://twitter.com/IIASAVienna?ref_src=twsrc%5Etfw">@IIASAVienna</a> <a href="https://t.co/hsOqYwMqIS">https://t.co/hsOqYwMqIS</a> <a href="https://t.co/MvcGMKqNbZ">pic.twitter.com/MvcGMKqNbZ</a></p>&mdash; Mariësse van Sluisveld (@marieyesse) <a href="https://twitter.com/marieyesse/status/861853470667685888?ref_src=twsrc%5Etfw">9 mei 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Do regional climate models add value compared to global models? <a href="https://t.co/cx4A0uggk9">https://t.co/cx4A0uggk9</a></p>&mdash; NatureClimate (@NatureClimate) <a href="https://twitter.com/NatureClimate/status/734652545352798209?ref_src=twsrc%5Etfw">23 mei 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New review paper on <a href="https://twitter.com/hashtag/OpenSource?src=hash&amp;ref_src=twsrc%5Etfw">#OpenSource</a> <a href="https://twitter.com/hashtag/Energy?src=hash&amp;ref_src=twsrc%5Etfw">#Energy</a> <a href="https://twitter.com/hashtag/Models?src=hash&amp;ref_src=twsrc%5Etfw">#Models</a>: &quot;The result shows that available open source tools such as Switch, TEMOA, OSeMOSYS, and pyPSA are mature enough based on a function comparison with commercial or proprietary tools for serious use.&quot;<a href="https://t.co/1OHzN87iGS">https://t.co/1OHzN87iGS</a> <a href="https://t.co/0ftqGfv1sH">pic.twitter.com/0ftqGfv1sH</a></p>&mdash; OpenMod Initiative (@openmod) <a href="https://twitter.com/openmod/status/1076505443646783488?ref_src=twsrc%5Etfw">22 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">To what extent are the main strands in modelling of socio-technological changes capable of coping with characteristics of sustainability transitions? A new review of modelling transitions <a href="https://twitter.com/JASSSJournal?ref_src=twsrc%5Etfw">@JASSSJournal</a> preview in <a href="https://t.co/dKlgYFl1jZ">https://t.co/dKlgYFl1jZ</a> <a href="https://t.co/Fj1YT4Jx28">pic.twitter.com/Fj1YT4Jx28</a></p>&mdash; Enayat Moallemi (@EnayatMoallemi) <a href="https://twitter.com/EnayatMoallemi/status/935993912140873729?ref_src=twsrc%5Etfw">29 november 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Scenario evaluation

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Many different studies have estimated the level of consensus about human induced warming. Four of those arrived at &gt;97%, the others at &gt;90%.<br>See <a href="https://t.co/sTGbmPx8pO">https://t.co/sTGbmPx8pO</a><br>or my blogpost about this paper (on which I&#39;m a co-author): <a href="https://t.co/qP2pNo7zua">https://t.co/qP2pNo7zua</a></p>&mdash; Bart Verheggen (@BVerheggen) <a href="https://twitter.com/BVerheggen/status/1081530706990415872?ref_src=twsrc%5Etfw">5 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">with 13 papers in the Special Issue, by <a href="https://twitter.com/josephrkasprzyk?ref_src=twsrc%5Etfw">@josephrkasprzyk</a> <a href="https://twitter.com/jan_kwakkel?ref_src=twsrc%5Etfw">@jan_kwakkel</a> <a href="https://twitter.com/VincentViguie?ref_src=twsrc%5Etfw">@VincentViguie</a> <a href="https://twitter.com/jfdecarolis?ref_src=twsrc%5Etfw">@jfdecarolis</a> <a href="https://twitter.com/lolow225?ref_src=twsrc%5Etfw">@lolow225</a> &amp; more: <a href="https://t.co/XrlSU5GSr9">https://t.co/XrlSU5GSr9</a> <a href="https://t.co/svQt9UmGbs">https://t.co/svQt9UmGbs</a></p>&mdash; Celine Guivarch (@CelineGuivarch) <a href="https://twitter.com/CelineGuivarch/status/903164016012513282?ref_src=twsrc%5Etfw">31 augustus 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New <a href="https://twitter.com/IPCC_CH?ref_src=twsrc%5Etfw">@IPCC_CH</a> expert meeting report on <a href="https://twitter.com/hashtag/climate?src=hash&amp;ref_src=twsrc%5Etfw">#climate</a> stabilization scenarios, incl. a brief discussion on &#39;feasibility&#39; <a href="https://t.co/Af7VtEbmxE">https://t.co/Af7VtEbmxE</a> <a href="https://t.co/f5nntwyUcK">pic.twitter.com/f5nntwyUcK</a></p>&mdash; Oliver Geden (@Oliver_Geden) <a href="https://twitter.com/Oliver_Geden/status/892045272649535488?ref_src=twsrc%5Etfw">31 juli 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New paper out today - Assessing carbon lock-in - <a href="http://t.co/gde3usVzma">http://t.co/gde3usVzma</a>   - how to assess the speed, strength, and scale of carbon lock-in</p>&mdash; Peter Erickson (@SEI_Erickson) <a href="https://twitter.com/SEI_Erickson/status/636266836892344320?ref_src=twsrc%5Etfw">25 augustus 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Nice take by <a href="https://twitter.com/vschweizer?ref_src=twsrc%5Etfw">@vschweizer</a> on implications of <a href="https://twitter.com/jr_lamontagne?ref_src=twsrc%5Etfw">@jr_lamontagne</a> Large Ensemble scenario discovery paper <a href="https://t.co/5KMtWYxCyR">https://t.co/5KMtWYxCyR</a> for future IAM research: <a href="https://t.co/KHk2PcWd9D">https://t.co/KHk2PcWd9D</a> <a href="https://twitter.com/deepuncertainty?ref_src=twsrc%5Etfw">@deepuncertainty</a></p>&mdash; Jan Kwakkel (@jan_kwakkel) <a href="https://twitter.com/jan_kwakkel/status/985959431459557377?ref_src=twsrc%5Etfw">16 april 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Happy to receive a signed version of Granger Morgan‘s new book „Theory and Practice in Policy Analysis“ <a href="https://twitter.com/CMU_EPP?ref_src=twsrc%5Etfw">@CMU_EPP</a>. What a resource for teaching and research! <a href="https://t.co/3HVrXnB56i">https://t.co/3HVrXnB56i</a></p>&mdash; Evelina Trutnevyte (@etrutnevyte) <a href="https://twitter.com/etrutnevyte/status/957538562181943296?ref_src=twsrc%5Etfw">28 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Expert elicitation

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Future Prospects for Energy Technologies in Review of Environmental Economics and Policy <a href="https://t.co/MUvv1tWeLw">https://t.co/MUvv1tWeLw</a></p>&mdash; Laurent Drouet (@lolow225) <a href="https://twitter.com/lolow225/status/961230019602407424?ref_src=twsrc%5Etfw">7 februari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Absolutely fantastic poster outlining cognitive biases. This should be compulsory to study before studying anything else. Or registering on Twitter. Or reading anything. Pls RT <a href="https://t.co/P30VgbwJyf">pic.twitter.com/P30VgbwJyf</a></p>&mdash; Tom Bennett (@tombennett71) <a href="https://twitter.com/tombennett71/status/987971607997149184?ref_src=twsrc%5Etfw">22 april 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Cheers to this cognitive bias cheat sheet! <a href="https://t.co/gDLMfHYxnd">https://t.co/gDLMfHYxnd</a> by <a href="https://twitter.com/buster?ref_src=twsrc%5Etfw">@buster</a> <a href="https://t.co/SOpwArCtdI">pic.twitter.com/SOpwArCtdI</a></p>&mdash; Violet (@mindthegreen) <a href="https://twitter.com/mindthegreen/status/785785195920326656?ref_src=twsrc%5Etfw">11 oktober 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Interesting read: Darkow et al. (2013) &quot;<a href="https://twitter.com/hashtag/Scenarios?src=hash&amp;ref_src=twsrc%5Etfw">#Scenarios</a> for the future of the <a href="https://twitter.com/hashtag/European?src=hash&amp;ref_src=twsrc%5Etfw">#European</a> process industry - the case of the <a href="https://twitter.com/hashtag/chemical?src=hash&amp;ref_src=twsrc%5Etfw">#chemical</a> industry&quot;, <a href="https://twitter.com/hashtag/expert?src=hash&amp;ref_src=twsrc%5Etfw">#expert</a>-based <a href="https://twitter.com/hashtag/scenarios?src=hash&amp;ref_src=twsrc%5Etfw">#scenarios</a> for future change in chemical industry by 2030 <a href="https://t.co/D7cZCmbq2f">https://t.co/D7cZCmbq2f</a> <a href="https://t.co/Hrr0gVLiEo">pic.twitter.com/Hrr0gVLiEo</a></p>&mdash; Mariësse van Sluisveld (@marieyesse) <a href="https://twitter.com/marieyesse/status/958042022362992641?ref_src=twsrc%5Etfw">29 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Interesting read: Toppinen et al. (2017) &quot;The <a href="https://twitter.com/hashtag/European?src=hash&amp;ref_src=twsrc%5Etfw">#European</a> <a href="https://twitter.com/hashtag/pulp?src=hash&amp;ref_src=twsrc%5Etfw">#pulp</a> and <a href="https://twitter.com/hashtag/paper?src=hash&amp;ref_src=twsrc%5Etfw">#paper</a> industry in <a href="https://twitter.com/hashtag/transition?src=hash&amp;ref_src=twsrc%5Etfw">#transition</a> to a bio-economy: A <a href="https://twitter.com/hashtag/Delphi?src=hash&amp;ref_src=twsrc%5Etfw">#Delphi</a> study&quot;, featuring a bottom-up <a href="https://twitter.com/hashtag/future?src=hash&amp;ref_src=twsrc%5Etfw">#future</a> <a href="https://twitter.com/hashtag/scenario?src=hash&amp;ref_src=twsrc%5Etfw">#scenario</a> towards 2030 for the paper industry <a href="https://t.co/UetL7Tzbyr">https://t.co/UetL7Tzbyr</a> <a href="https://t.co/u7KIBVsnum">pic.twitter.com/u7KIBVsnum</a></p>&mdash; Mariësse van Sluisveld (@marieyesse) <a href="https://twitter.com/marieyesse/status/958037597309284358?ref_src=twsrc%5Etfw">29 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Mental Models I Find Repeatedly Useful: <a href="https://t.co/ibgMmTNKwa">https://t.co/ibgMmTNKwa</a> <a href="https://t.co/jPbx3hDpnW">pic.twitter.com/jPbx3hDpnW</a></p>&mdash; David Bijl (@davidbijl) <a href="https://twitter.com/davidbijl/status/857860674613104640?ref_src=twsrc%5Etfw">28 april 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">People Have Had Enough of Experts, provocative (but true) title for an interesting blog post by <a href="https://twitter.com/INETeconomics?ref_src=twsrc%5Etfw">@INETeconomics</a> : <a href="https://t.co/cziXOQKp22">https://t.co/cziXOQKp22</a></p>&mdash; Celine Guivarch (@CelineGuivarch) <a href="https://twitter.com/CelineGuivarch/status/839791107865210880?ref_src=twsrc%5Etfw">9 maart 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Consider stakeholder preferences and knowledge for low-emission transition pathways <a href="https://t.co/cLGH5U0WjP">https://t.co/cLGH5U0WjP</a> <a href="https://twitter.com/hashtag/mitigationEU?src=hash&amp;ref_src=twsrc%5Etfw">#mitigationEU</a> <a href="https://twitter.com/TRANSrisk_EU?ref_src=twsrc%5Etfw">@TRANSrisk_EU</a></p>&mdash; CARISMA project (@CarismaEU) <a href="https://twitter.com/CarismaEU/status/820933305239478272?ref_src=twsrc%5Etfw">16 januari 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Comment: Breaking cognitive barriers to a sustainable future <a href="https://twitter.com/NatureHumBehav?ref_src=twsrc%5Etfw">@NatureHumBehav</a>  <a href="https://t.co/LLGohCqsIl">https://t.co/LLGohCqsIl</a></p>&mdash; NatureClimate (@NatureClimate) <a href="https://twitter.com/NatureClimate/status/822798654280900610?ref_src=twsrc%5Etfw">21 januari 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">A systematic review of transparency in the methods of expert knowledge use <a href="https://t.co/998bpxu9QM">https://t.co/998bpxu9QM</a></p>&mdash; Jeroen van der Sluijs (@Jeroen_vdSluijs) <a href="https://twitter.com/Jeroen_vdSluijs/status/1051050172044722177?ref_src=twsrc%5Etfw">13 oktober 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">We must manage systems with little data. Fuzzy cognitive maps (FCMs) are a helpful tool. We provide guidelines for using FCMs w expert elicitation to manage <a href="https://twitter.com/hashtag/networks?src=hash&amp;ref_src=twsrc%5Etfw">#networks</a> in a paper lead by the awesome <a href="https://twitter.com/cbaker_research?ref_src=twsrc%5Etfw">@cbaker_research</a> <a href="https://t.co/OiqAV9IowC">https://t.co/OiqAV9IowC</a> bc its easy to use them incorrectly <a href="https://t.co/jnIdx4Imlx">pic.twitter.com/jnIdx4Imlx</a></p>&mdash; Matthew Holden (@MattHHolden) <a href="https://twitter.com/MattHHolden/status/1004569379319627776?ref_src=twsrc%5Etfw">7 juni 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/IPCC?src=hash&amp;ref_src=twsrc%5Etfw">#IPCC</a> authors subscribe to value-free ideal in their role as experts. Yet their views on the moral responsibility of scientists and the aim of providing policy-relevant output challenge this ideal. <br>Interesting <a href="https://twitter.com/arena_uio?ref_src=twsrc%5Etfw">@arena_uio</a> working paper by T. Gundersen<a href="https://t.co/RuYk3F0WSH">https://t.co/RuYk3F0WSH</a></p>&mdash; Oliver Geden (@Oliver_Geden) <a href="https://twitter.com/Oliver_Geden/status/987684886571077632?ref_src=twsrc%5Etfw">21 april 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Transition indicators

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">We&#39;ve published an Energy Efficiency Indicators database for the first time, with annual data from 2000-2015 <a href="https://t.co/WNJdIZYC5n">https://t.co/WNJdIZYC5n</a> <a href="https://t.co/ZfrORrdFNU">pic.twitter.com/ZfrORrdFNU</a></p>&mdash; IEA (@IEA) <a href="https://twitter.com/IEA/status/969981106866081794?ref_src=twsrc%5Etfw">3 maart 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Are we on track to &lt;2C?<br>Out of 26 indicators:<br>* 3 on track<br>* 15 more efforts needed<br>* 8 not on track<a href="https://t.co/DuxXWbFbOH">https://t.co/DuxXWbFbOH</a> <a href="https://t.co/uLuQKyLEwO">pic.twitter.com/uLuQKyLEwO</a></p>&mdash; Glen Peters (@Peters_Glen) <a href="https://twitter.com/Peters_Glen/status/865104166326222848?ref_src=twsrc%5Etfw">18 mei 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Check it out! Now in English. NL indicators on nature, environment,  space <a href="https://t.co/JxttRj4Juc">https://t.co/JxttRj4Juc</a> <a href="https://twitter.com/hashtag/PBLNL?src=hash&amp;ref_src=twsrc%5Etfw">#PBLNL</a> <a href="https://twitter.com/hashtag/opendata?src=hash&amp;ref_src=twsrc%5Etfw">#opendata</a> <a href="https://t.co/BOInxuTBiQ">pic.twitter.com/BOInxuTBiQ</a></p>&mdash; hansmommaas (@hansmms) <a href="https://twitter.com/hansmms/status/743195428473151488?ref_src=twsrc%5Etfw">15 juni 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">📢 The 2018 <a href="https://twitter.com/hashtag/EUindustry?src=hash&amp;ref_src=twsrc%5Etfw">#EUindustry</a> R&amp;D Scoreboard is out! <br><br>In 2017, companies in the EU 🇪🇺 invested 5.5% more in R&amp;D activities than the year before 👉 <a href="https://t.co/VvdK7Qfvry">https://t.co/VvdK7Qfvry</a><a href="https://twitter.com/hashtag/InvestEUresearch?src=hash&amp;ref_src=twsrc%5Etfw">#InvestEUresearch</a> <a href="https://t.co/u4PFdagloJ">pic.twitter.com/u4PFdagloJ</a></p>&mdash; EU_ScienceHub (@EU_ScienceHub) <a href="https://twitter.com/EU_ScienceHub/status/1074648931529822208?ref_src=twsrc%5Etfw">17 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Towards a scientific basis for the number <a href="https://twitter.com/hashtag/environment?src=hash&amp;ref_src=twsrc%5Etfw">#environment</a> <a href="https://twitter.com/hashtag/headline?src=hash&amp;ref_src=twsrc%5Etfw">#headline</a> indicators<a href="https://t.co/RZP0OehsDq">https://t.co/RZP0OehsDq</a><a href="https://twitter.com/EUEnvironment?ref_src=twsrc%5Etfw">@EUEnvironment</a> <a href="https://twitter.com/EU_ENV?ref_src=twsrc%5Etfw">@EU_ENV</a> <a href="https://t.co/pAnr5ePT8Q">pic.twitter.com/pAnr5ePT8Q</a></p>&mdash; Konstantin Stadler (@kst_stadler) <a href="https://twitter.com/kst_stadler/status/926040084180340737?ref_src=twsrc%5Etfw">2 november 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Co-creation / participatory work

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Participatory research is a fabulous way to co-design sustainability solutions but also has some largely unrecognized challenges and risks. We explore those and outline management strategies here <a href="https://t.co/pEafMFqRw1">https://t.co/pEafMFqRw1</a><a href="https://twitter.com/ChrisCvitanovic?ref_src=twsrc%5Etfw">@ChrisCvitanovic</a> <a href="https://twitter.com/bec_colvin?ref_src=twsrc%5Etfw">@bec_colvin</a> <a href="https://twitter.com/AlbertNorstrm?ref_src=twsrc%5Etfw">@AlbertNorstrm</a> <a href="https://twitter.com/prueaddison?ref_src=twsrc%5Etfw">@prueaddison</a></p>&mdash; Mark Howden (@ProfMarkHowden) <a href="https://twitter.com/ProfMarkHowden/status/1083680603617153025?ref_src=twsrc%5Etfw">11 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New comment <a href="https://twitter.com/naturesustainab?ref_src=twsrc%5Etfw">@naturesustainab</a> looks @ promise &amp; peril of knowledge co-production—urges scientists, stakeholders &amp; funders to better understand how to invest/support co-production so that it leads to sustainability outcomes &amp; isn&#39;t an end in itself <a href="https://t.co/DsbvhsMFB8">https://t.co/DsbvhsMFB8</a> <a href="https://t.co/pz9r3C7PiY">pic.twitter.com/pz9r3C7PiY</a></p>&mdash; Chris Field (@chrfield) <a href="https://twitter.com/chrfield/status/1074745820589617152?ref_src=twsrc%5Etfw">17 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Perhaps of interest: Tools and methods for participatory modeling - <a href="https://t.co/0EdF6BcmwO">https://t.co/0EdF6BcmwO</a></p>&mdash; Alexey Voinov (@alexeyvoinov) <a href="https://twitter.com/alexeyvoinov/status/1039427358686498816?ref_src=twsrc%5Etfw">11 september 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Design guidelines to a <a href="https://twitter.com/hashtag/participatory?src=hash&amp;ref_src=twsrc%5Etfw">#participatory</a> process by Dr Armin Wiek - hitting straight into our rigour and relevance with our upcoming <a href="https://twitter.com/hashtag/industry?src=hash&amp;ref_src=twsrc%5Etfw">#industry</a> <a href="https://twitter.com/hashtag/stakeholder?src=hash&amp;ref_src=twsrc%5Etfw">#stakeholder</a> workshops <a href="https://twitter.com/hashtag/UUpathways?src=hash&amp;ref_src=twsrc%5Etfw">#UUpathways</a> <a href="https://t.co/8uTKFjuoz4">pic.twitter.com/8uTKFjuoz4</a></p>&mdash; REINVENT (@REINVENT_EU) <a href="https://twitter.com/REINVENT_EU/status/961928669261369344?ref_src=twsrc%5Etfw">9 februari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Mike Hulme mentions Scott&#39;s and my study on the use of &#39;co-production&#39; in climate change research as exemplary systematic review paper :-) Go and see yourself: <a href="https://t.co/WRECclDedz">https://t.co/WRECclDedz</a></p>&mdash; Simon Meisch (@simon_meisch) <a href="https://twitter.com/simon_meisch/status/952545856598790145?ref_src=twsrc%5Etfw">14 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Looking at long-term planning of <a href="https://twitter.com/hashtag/energy?src=hash&amp;ref_src=twsrc%5Etfw">#energy</a> <a href="https://twitter.com/hashtag/transitions?src=hash&amp;ref_src=twsrc%5Etfw">#transitions</a> from a participatory exploratory modelling perspective. With Shirin Malekpour <a href="https://twitter.com/MonashMSDI?ref_src=twsrc%5Etfw">@MonashMSDI</a> in SI: Energy &amp; the Future, Energy Res. Soc. Sci. Download from: <a href="https://t.co/q0M6DLBd4S">https://t.co/q0M6DLBd4S</a> <a href="https://t.co/2Cv7qPoeiM">pic.twitter.com/2Cv7qPoeiM</a></p>&mdash; Enayat Moallemi (@EnayatMoallemi) <a href="https://twitter.com/EnayatMoallemi/status/963298147744149504?ref_src=twsrc%5Etfw">13 februari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">I agree, it is indeed an exemplary systematic review paper on co-production in climate change research! <a href="https://twitter.com/hashtag/coproduction?src=hash&amp;ref_src=twsrc%5Etfw">#coproduction</a> <a href="https://twitter.com/hashtag/cocreation?src=hash&amp;ref_src=twsrc%5Etfw">#cocreation</a> <a href="https://twitter.com/hashtag/postnormalscience?src=hash&amp;ref_src=twsrc%5Etfw">#postnormalscience</a> <a href="https://twitter.com/hashtag/PNS?src=hash&amp;ref_src=twsrc%5Etfw">#PNS</a>  <a href="https://twitter.com/hashtag/transdisciplinarity?src=hash&amp;ref_src=twsrc%5Etfw">#transdisciplinarity</a> <a href="https://t.co/iRGa3Gqc3p">https://t.co/iRGa3Gqc3p</a></p>&mdash; Jeroen van der Sluijs (@Jeroen_vdSluijs) <a href="https://twitter.com/Jeroen_vdSluijs/status/952550342771838977?ref_src=twsrc%5Etfw">14 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Read our newly published piece on innovative participatory research methods written following the 2016 <a href="https://twitter.com/ESG_Project?ref_src=twsrc%5Etfw">@ESG_Project</a> Annual Conference 2016, by <a href="https://twitter.com/Vervoort_Joost?ref_src=twsrc%5Etfw">@Vervoort_Joost</a> <a href="https://twitter.com/GreetjeSchouten?ref_src=twsrc%5Etfw">@GreetjeSchouten</a> <a href="https://twitter.com/LucasRutting?ref_src=twsrc%5Etfw">@LucasRutting</a> <a href="https://twitter.com/MariekeVeeger?ref_src=twsrc%5Etfw">@MariekeVeeger</a> Karsten Schulz and Jennifer Garard, in <a href="https://twitter.com/ARSPnews?ref_src=twsrc%5Etfw">@ARSPnews</a> : <a href="https://t.co/j98GXujCMg">https://t.co/j98GXujCMg</a></p>&mdash; Marijn Faling (@MarijnFaling) <a href="https://twitter.com/MarijnFaling/status/943765962477752320?ref_src=twsrc%5Etfw">21 december 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Futuring / Narratives / Scenarios

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New reads to keep me off the streets: &quot;Narratives and Storytelling in Energy and Climate Change Research&quot; <a href="https://t.co/6sWaVe3JVa">https://t.co/6sWaVe3JVa</a> <a href="https://t.co/sHvVQBWZtZ">pic.twitter.com/sHvVQBWZtZ</a></p>&mdash; Mariësse van Sluisveld (@marieyesse) <a href="https://twitter.com/marieyesse/status/922388109635055617?ref_src=twsrc%5Etfw">23 oktober 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">A short comment on why scenario development needs to be more systematic and more transparent   <a href="https://t.co/ZXFSgYZUUV">https://t.co/ZXFSgYZUUV</a></p>&mdash; Henrik Carlsen (@HCarlsen_SEI) <a href="https://twitter.com/HCarlsen_SEI/status/903514730467385344?ref_src=twsrc%5Etfw">1 september 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Colleague and futures researcher Dr <a href="https://twitter.com/Vervoort_Joost?ref_src=twsrc%5Etfw">@Vervoort_Joost</a> was interviewed about the benefits of bottom-up thinking in this <a href="https://twitter.com/PNASNews?ref_src=twsrc%5Etfw">@PNASNews</a> piece &quot;Science and Culture: Imagining a climate-change future, without the dystopia&quot;. Read here: <a href="https://t.co/iOTtejNpV9">https://t.co/iOTtejNpV9</a> <a href="https://t.co/s0HEcC16et">pic.twitter.com/s0HEcC16et</a></p>&mdash; Copernicus Institute of Sustainable Development UU (@UUCopernicus) <a href="https://twitter.com/UUCopernicus/status/1075385233682374656?ref_src=twsrc%5Etfw">19 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Great read this <a href="https://twitter.com/IMPRESSIONS_EU?ref_src=twsrc%5Etfw">@IMPRESSIONS_EU</a> paper on bridging uncertainty concepts to link qualitative and quantitative <a href="https://twitter.com/hashtag/scenarios?src=hash&amp;ref_src=twsrc%5Etfw">#scenarios</a>. Looking forward to reading the full special issue in Regional Environmental Change <a href="https://t.co/OIF3YyLAx9">https://t.co/OIF3YyLAx9</a></p>&mdash; Jan Kuiper (@jankuiper87) <a href="https://twitter.com/jankuiper87/status/994939532159193088?ref_src=twsrc%5Etfw">11 mei 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">First RE-IMAGINE paper is out! &quot;Anticipating climate futures in a 1.5°C era: the link between foresight and governance&quot; by <a href="https://twitter.com/Vervoort_Joost?ref_src=twsrc%5Etfw">@Vervoort_Joost</a> (UU) and Aarti Gupta (WUR) is available at <a href="https://t.co/U8tuMM86Qy">https://t.co/U8tuMM86Qy</a> <a href="https://twitter.com/UUCopernicus?ref_src=twsrc%5Etfw">@UUCopernicus</a> <a href="https://twitter.com/ENPWageningen?ref_src=twsrc%5Etfw">@ENPWageningen</a> <a href="https://twitter.com/WUR?ref_src=twsrc%5Etfw">@WUR</a> <a href="https://twitter.com/UniUtrecht?ref_src=twsrc%5Etfw">@UniUtrecht</a></p>&mdash; RE-IMAGINE Project (@_RE_IMAGINE_) <a href="https://twitter.com/_RE_IMAGINE_/status/966655062599663616?ref_src=twsrc%5Etfw">22 februari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Interdisciplinarity

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">.<a href="https://twitter.com/PATHWAYS_EU?ref_src=twsrc%5Etfw">@PATHWAYS_EU</a>: Constructive dialogue key in catalyzing collaborative research: see <a href="https://t.co/PrWGTjPNll">https://t.co/PrWGTjPNll</a> <a href="https://t.co/BChoYL1nfv">pic.twitter.com/BChoYL1nfv</a></p>&mdash; Mariësse van Sluisveld (@marieyesse) <a href="https://twitter.com/marieyesse/status/670265243449315330?ref_src=twsrc%5Etfw">27 november 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Finally, after years of hard work and perfection, and in the mean time inspired a dozen papers applying the same concept, the original and most complete paper of incorporating consumer choice in bottom-up models is now published <a href="https://t.co/C0QeTLnVW4">https://t.co/C0QeTLnVW4</a> Congrats 🎉 <a href="https://twitter.com/KalaiRamea?ref_src=twsrc%5Etfw">@KalaiRamea</a></p>&mdash; Sonia Yeh (@Sonia_Yeh) <a href="https://twitter.com/Sonia_Yeh/status/1024162131124600833?ref_src=twsrc%5Etfw">31 juli 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Just published in <a href="https://twitter.com/NatureClimate?ref_src=twsrc%5Etfw">@NatureClimate</a>: Understanding and managing trust at the climate science–policy interface. Read it here - <a href="https://t.co/gXbkhhrc3G">https://t.co/gXbkhhrc3G</a> <a href="https://t.co/LoATZu2kI5">pic.twitter.com/LoATZu2kI5</a></p>&mdash; Chris Cvitanovic (@ChrisCvitanovic) <a href="https://twitter.com/ChrisCvitanovic/status/942857200774537216?ref_src=twsrc%5Etfw">18 december 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Techno-economic, socio-technical and political perspective on <a href="https://twitter.com/hashtag/energytransition?src=hash&amp;ref_src=twsrc%5Etfw">#energytransition</a>  <a href="https://t.co/CLleqPFV86">https://t.co/CLleqPFV86</a></p>&mdash; Evelina Trutnevyte (@etrutnevyte) <a href="https://twitter.com/etrutnevyte/status/942633632266706944?ref_src=twsrc%5Etfw">18 december 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Great to see in Science, even without transition governance: Sociotechnical transitions for deep decarbonization: <a href="https://t.co/SSbNNxMI5i">https://t.co/SSbNNxMI5i</a></p>&mdash; Derk Loorbach (@drk75) <a href="https://twitter.com/drk75/status/911165311113728002?ref_src=twsrc%5Etfw">22 september 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">The climate mitigation gap: education and government recommendations miss the most effective individual actions <a href="https://t.co/0Tzr5UDLWq">https://t.co/0Tzr5UDLWq</a></p>&mdash; Mariësse van Sluisveld (@marieyesse) <a href="https://twitter.com/marieyesse/status/885425436318208000?ref_src=twsrc%5Etfw">13 juli 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">This collection by <a href="https://twitter.com/NatureClimate?ref_src=twsrc%5Etfw">@NatureClimate</a> &amp; <a href="https://twitter.com/NatureEnergyJnl?ref_src=twsrc%5Etfw">@NatureEnergyJnl</a> shows the trend: engaging social sciences in energy transitions <a href="https://t.co/4U4ud8mijr">https://t.co/4U4ud8mijr</a></p>&mdash; Brigitte Knopf (@BrigitteKnopf) <a href="https://twitter.com/BrigitteKnopf/status/730248940667453441?ref_src=twsrc%5Etfw">11 mei 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Climate science needs deep collaboration with social sciences and humanities. Our latest piece on this in <a href="https://twitter.com/NatureClimate?ref_src=twsrc%5Etfw">@NatureClimate</a>.<br><br>A viewable version is at <a href="https://t.co/vNU8ALUgzl">https://t.co/vNU8ALUgzl</a>. To download, go to <a href="https://t.co/aRaxEs4G8u">https://t.co/aRaxEs4G8u</a>. <a href="https://twitter.com/AASWSWorg?ref_src=twsrc%5Etfw">@aaswsworg</a> <a href="https://twitter.com/utkcsw?ref_src=twsrc%5Etfw">@utkcsw</a> <a href="https://twitter.com/csdwustl?ref_src=twsrc%5Etfw">@csdwustl</a> <a href="https://twitter.com/hashtag/utknoxville?src=hash&amp;ref_src=twsrc%5Etfw">#utknoxville</a> <a href="https://twitter.com/hashtag/socialwork?src=hash&amp;ref_src=twsrc%5Etfw">#socialwork</a></p>&mdash; Lisa Reyes Mason (@LisaReyesMason) <a href="https://twitter.com/LisaReyesMason/status/1068537782417666048?ref_src=twsrc%5Etfw">30 november 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Good contribution to the development of transdisciplinary research for <a href="https://twitter.com/hashtag/sustainability?src=hash&amp;ref_src=twsrc%5Etfw">#sustainability</a> <a href="https://twitter.com/hashtag/transitions?src=hash&amp;ref_src=twsrc%5Etfw">#transitions</a>, although it misses a bit the idea that we need new methodology to make this happen (like transition arena): <a href="https://t.co/204YupsNN6">https://t.co/204YupsNN6</a></p>&mdash; Derk Loorbach (@drk75) <a href="https://twitter.com/drk75/status/957584424295653376?ref_src=twsrc%5Etfw">28 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Paradigms & Shifts

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Is least cost-modelling the best way to develop feasible scenarios? <br>We examined this question in a paper called The Socio-Political Merit-Order: <a href="https://t.co/BKD7o8isbs">https://t.co/BKD7o8isbs</a></p>&mdash; Kornelis Blok (@KornelisBlok) <a href="https://twitter.com/KornelisBlok/status/987236017743761408?ref_src=twsrc%5Etfw">20 april 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Uncertainty

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Bridging uncertainty concepts across narratives and simulations in environmental scenarios<br>Pedde+<a href="https://t.co/jRG0BUiRrf">https://t.co/jRG0BUiRrf</a> <a href="https://t.co/q0RL5EL46Z">pic.twitter.com/q0RL5EL46Z</a></p>&mdash; Garry Peterson (@resilienceSci) <a href="https://twitter.com/resilienceSci/status/996355849227505665?ref_src=twsrc%5Etfw">15 mei 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Our new article with <a href="https://twitter.com/IPSL_outreach?ref_src=twsrc%5Etfw">@IPSL_outreach</a> colleagues is out: Impacts of nationally determined contributions on 2030 global greenhouse gas emissions: uncertainty analysis and distribution of emissions <a href="https://t.co/Z7c74llz3V">https://t.co/Z7c74llz3V</a> via <a href="https://twitter.com/IOPscience?ref_src=twsrc%5Etfw">@IOPscience</a> <a href="https://twitter.com/cired8568?ref_src=twsrc%5Etfw">@cired8568</a></p>&mdash; Celine Guivarch (@CelineGuivarch) <a href="https://twitter.com/CelineGuivarch/status/954281236813549568?ref_src=twsrc%5Etfw">19 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">‘Integrating uncertainty into public energy research and development decisions’ Read <a href="https://twitter.com/l_diaz_anadon?ref_src=twsrc%5Etfw">@l_diaz_anadon</a> paper in <a href="https://twitter.com/NatureEnergyJnl?ref_src=twsrc%5Etfw">@NatureEnergyJnl</a> <a href="https://t.co/YeooBYtBby">https://t.co/YeooBYtBby</a></p>&mdash; INNOPATHS (@innopathsEU) <a href="https://twitter.com/innopathsEU/status/943434102287556609?ref_src=twsrc%5Etfw">20 december 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">NEW PAPER: what do experts view as the critical uncertainties in delivering climate objectives of Clean Growth Plan? <a href="https://t.co/5hiWI3qlkO">https://t.co/5hiWI3qlkO</a> <a href="https://t.co/mI0ZZ6sppy">pic.twitter.com/mI0ZZ6sppy</a></p>&mdash; Steve Pye (@st_pye) <a href="https://twitter.com/st_pye/status/918065715109941248?ref_src=twsrc%5Etfw">11 oktober 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Post normal science in practice: open access special issue <a href="https://twitter.com/hashtag/PNS?src=hash&amp;ref_src=twsrc%5Etfw">#PNS</a> <a href="https://twitter.com/hashtag/postnormalscience?src=hash&amp;ref_src=twsrc%5Etfw">#postnormalscience</a> <a href="https://twitter.com/hashtag/post_normal_science?src=hash&amp;ref_src=twsrc%5Etfw">#post_normal_science</a> <a href="https://twitter.com/hashtag/PNS3?src=hash&amp;ref_src=twsrc%5Etfw">#PNS3</a> <a href="https://t.co/aDZZSLt8Eu">https://t.co/aDZZSLt8Eu</a> <a href="https://t.co/sByYCPe634">pic.twitter.com/sByYCPe634</a></p>&mdash; Jeroen van der Sluijs (@Jeroen_vdSluijs) <a href="https://twitter.com/Jeroen_vdSluijs/status/909670141968945152?ref_src=twsrc%5Etfw">18 september 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">&quot;The epistemic, ethical, and political dimensions of uncertainty in IAMs&quot; - very interesting <a href="https://twitter.com/WIREs_Climate?ref_src=twsrc%5Etfw">@WIREs_Climate</a> article <a href="https://t.co/d6WndNgsf0">https://t.co/d6WndNgsf0</a></p>&mdash; Oliver Geden (@Oliver_Geden) <a href="https://twitter.com/Oliver_Geden/status/767010051982712832?ref_src=twsrc%5Etfw">20 augustus 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Struggle to tell your epistemological from your ontological stance? Not sure how postmodernism differs from poststructuralism? And what is phenomenology anyway? This looks like a great paper for understanding how social scientists approach research: <a href="https://t.co/wr7ReCvB5p">https://t.co/wr7ReCvB5p</a></p>&mdash; Bregje van Veelen (@bvanveelen) <a href="https://twitter.com/bvanveelen/status/1052655677364207621?ref_src=twsrc%5Etfw">17 oktober 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">NEW ERSS PAPER from <a href="https://twitter.com/UCL_Energy?ref_src=twsrc%5Etfw">@UCL_Energy</a> and <a href="https://twitter.com/UCLSTEaPP?ref_src=twsrc%5Etfw">@UCLSTEaPP</a> highlighting the need to better scrutinise via expert elicitation key underlying assumptions in models that inform climate mitigation policy <a href="https://t.co/81hJdnsXnq">https://t.co/81hJdnsXnq</a> <a href="https://t.co/Ln21pbhZr3">pic.twitter.com/Ln21pbhZr3</a></p>&mdash; Steve Pye (@st_pye) <a href="https://twitter.com/st_pye/status/1031468213459148800?ref_src=twsrc%5Etfw">20 augustus 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Characterizing uncertainty in energy system optimization models using <a href="https://twitter.com/hashtag/NUSAP?src=hash&amp;ref_src=twsrc%5Etfw">#NUSAP</a> - my new paper with <a href="https://twitter.com/st_pye?ref_src=twsrc%5Etfw">@st_pye</a> <a href="https://twitter.com/fgnli?ref_src=twsrc%5Etfw">@fgnli</a> and others at <a href="https://twitter.com/UCL_Energy?ref_src=twsrc%5Etfw">@UCL_Energy</a> and <a href="https://twitter.com/UCLSTEaPP?ref_src=twsrc%5Etfw">@UCLSTEaPP</a>.  <a href="https://t.co/RZeqDI2WWk">https://t.co/RZeqDI2WWk</a></p>&mdash; Will McDowall (@Will_McDowall) <a href="https://twitter.com/Will_McDowall/status/1031462312228646912?ref_src=twsrc%5Etfw">20 augustus 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">How do we analyse uncertainty using energy models? Our new paper from <a href="https://twitter.com/MaREIcentre?ref_src=twsrc%5Etfw">@MaREIcentre</a> <a href="https://twitter.com/UCL_Energy?ref_src=twsrc%5Etfw">@UCL_Energy</a> <a href="https://twitter.com/NCState?ref_src=twsrc%5Etfw">@NCState</a> comprehensively reviews the approaches and proposes guidance for the use of different methods <a href="https://t.co/FCl4FylY4a">https://t.co/FCl4FylY4a</a> <a href="https://t.co/8jix4QZwl8">pic.twitter.com/8jix4QZwl8</a></p>&mdash; Steve Pye (@st_pye) <a href="https://twitter.com/st_pye/status/1022239340376801280?ref_src=twsrc%5Etfw">25 juli 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Non-Electricity 

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Yes, radical innovation is needed but it is characteristic that reducing energy demand is not mentioned <a href="https://t.co/YRfL4BmRT3">https://t.co/YRfL4BmRT3</a> <a href="https://twitter.com/hashtag/climate?src=hash&amp;ref_src=twsrc%5Etfw">#climate</a></p>&mdash; Maarten Hajer (@maartenhajer) <a href="https://twitter.com/maartenhajer/status/670194370906365952?ref_src=twsrc%5Etfw">27 november 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">50% of the EU&#39;s energy demand comes from heating and cooling. Insights on how to <a href="https://twitter.com/hashtag/decarbonise?src=hash&amp;ref_src=twsrc%5Etfw">#decarbonise</a> and the role of <a href="https://twitter.com/hashtag/renewables?src=hash&amp;ref_src=twsrc%5Etfw">#renewables</a>. <a href="https://t.co/njl084Qcm1">https://t.co/njl084Qcm1</a> via <a href="https://twitter.com/eaEnergyEU?ref_src=twsrc%5Etfw">@eaEnergyEU</a></p>&mdash; S2S4E (@S2S4E) <a href="https://twitter.com/S2S4E/status/977258381248516096?ref_src=twsrc%5Etfw">23 maart 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/Heat?src=hash&amp;ref_src=twsrc%5Etfw">#Heat</a> <a href="https://twitter.com/hashtag/Roadmap?src=hash&amp;ref_src=twsrc%5Etfw">#Roadmap</a> <a href="https://twitter.com/hashtag/Europe?src=hash&amp;ref_src=twsrc%5Etfw">#Europe</a>: Quantitative comparison between the electricity, heating, and cooling sectors <a href="https://t.co/J5IkjJcfgp">https://t.co/J5IkjJcfgp</a> <a href="https://twitter.com/hashtag/EU?src=hash&amp;ref_src=twsrc%5Etfw">#EU</a> <a href="https://twitter.com/hashtag/Energy?src=hash&amp;ref_src=twsrc%5Etfw">#Energy</a> <a href="https://t.co/JFoSbmuOFk">pic.twitter.com/JFoSbmuOFk</a></p>&mdash; HeatRoadmap Europe (@HeatRoadmapEU) <a href="https://twitter.com/HeatRoadmapEU/status/926073998907269123?ref_src=twsrc%5Etfw">2 november 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Decarbonising the heat sector <a href="https://t.co/pOY9zsjcQM">https://t.co/pOY9zsjcQM</a> via <a href="https://twitter.com/ShareThis?ref_src=twsrc%5Etfw">@sharethis</a> a new <a href="https://twitter.com/UKERCHQ?ref_src=twsrc%5Etfw">@UKERCHQ</a> blog from our Chair, Keith MacLean</p>&mdash; UKERC (@UKERCHQ) <a href="https://twitter.com/UKERCHQ/status/730788001404588032?ref_src=twsrc%5Etfw">12 mei 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">I wanted to cover this report (but there&#39;s only one of me). A hugely important topic: how to decarbonize the non-electricity, non-sexy sectors of the economy. <a href="https://t.co/ahtAGlbWyF">https://t.co/ahtAGlbWyF</a></p>&mdash; David Roberts (@drvox) <a href="https://twitter.com/drvox/status/1064996347651141632?ref_src=twsrc%5Etfw">20 november 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Decarbonising the heating and cooling sectors requires multiple technologies and innovative policies to implement <a href="https://twitter.com/hashtag/energyefficiency?src=hash&amp;ref_src=twsrc%5Etfw">#energyefficiency</a> and <a href="https://twitter.com/hashtag/districtheating?src=hash&amp;ref_src=twsrc%5Etfw">#districtheating</a>. <a href="https://twitter.com/hashtag/smartenergysystems?src=hash&amp;ref_src=twsrc%5Etfw">#smartenergysystems</a> <a href="https://twitter.com/hashtag/districtenergy?src=hash&amp;ref_src=twsrc%5Etfw">#districtenergy</a> <a href="https://twitter.com/hashtag/heatingEU?src=hash&amp;ref_src=twsrc%5Etfw">#heatingEU</a> <a href="https://twitter.com/hashtag/renewableenergy?src=hash&amp;ref_src=twsrc%5Etfw">#renewableenergy</a><br>&gt;<a href="https://t.co/MMVNo6mtp5">https://t.co/MMVNo6mtp5</a> <a href="https://t.co/BGq0HtxlVa">pic.twitter.com/BGq0HtxlVa</a></p>&mdash; Brian Vad Mathiesen (@BrianVad) <a href="https://twitter.com/BrianVad/status/1034170042282323974?ref_src=twsrc%5Etfw">27 augustus 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">On how to manage the costs of CO2 abatement in the cement industry <a href="https://t.co/mAA0VrV9ai">https://t.co/mAA0VrV9ai</a> and <br>pay the full price of steel <a href="https://t.co/8WVtNWK5p8">https://t.co/8WVtNWK5p8</a> <a href="https://t.co/olNPdtjeoP">pic.twitter.com/olNPdtjeoP</a></p>&mdash; Johan Rootzén (@JMRootzen) <a href="https://twitter.com/JMRootzen/status/1009785754304831488?ref_src=twsrc%5Etfw">21 juni 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Learn more about the limitations of and improvement options for integrated assessment models <a href="https://twitter.com/hashtag/IAM?src=hash&amp;ref_src=twsrc%5Etfw">#IAM</a> <a href="https://t.co/Xe0CMoMpQ9">https://t.co/Xe0CMoMpQ9</a></p>&mdash; Stefan Pauliuk (@StefanPauliuk) <a href="https://twitter.com/StefanPauliuk/status/935965725801566208?ref_src=twsrc%5Etfw">29 november 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Timely publication in light of this morning&#39;s discussion on &#39;what is social innovation?&#39; <a href="https://twitter.com/REINVENT_EU?ref_src=twsrc%5Etfw">@REINVENT_EU</a> <a href="https://t.co/7zs9nkZ1Rn">https://t.co/7zs9nkZ1Rn</a></p>&mdash; Bregje van Veelen (@bvanveelen) <a href="https://twitter.com/bvanveelen/status/935440097457172480?ref_src=twsrc%5Etfw">28 november 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## R tricks / Methods
<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🍿 Siri, cancel my weekend plans…<br>🎥 &quot;rstudio::conf 2019&quot; <a href="https://t.co/At0vxZUFCi">https://t.co/At0vxZUFCi</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> <a href="https://t.co/Z8KBltZKN7">pic.twitter.com/Z8KBltZKN7</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1088794504101089281?ref_src=twsrc%5Etfw">25 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>



<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🤯bookdown w/ runable exercises, &amp; interactive JS extensions…<br>📕 &quot;Introduction to Econometrics w/ R&quot;  by Christoph Hanck, Martin Arnold, Alexander Gerber &amp; Martin Schmelzer <a href="https://t.co/SgP9CYDKkZ">https://t.co/SgP9CYDKkZ</a><a href="https://t.co/WQkb3FWJp9">https://t.co/WQkb3FWJp9</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/repeatTweet?src=hash&amp;ref_src=twsrc%5Etfw">#repeatTweet</a> <a href="https://t.co/vj017el7u4">pic.twitter.com/vj017el7u4</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1083087575781396482?ref_src=twsrc%5Etfw">9 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">The tidyeval bookdown is 🔥🔥🔥.<br><br>If one of your 2019 <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> goals was to learn tidyeval, check it out!<a href="https://t.co/nxzAivN1IK">https://t.co/nxzAivN1IK</a><a href="https://twitter.com/hashtag/Tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#Tidyverse</a></p>&mdash; Thomas Mock 👨🏼
💻 (@thomas_mock) <a href="https://twitter.com/thomas_mock/status/1081966197204234240?ref_src=twsrc%5Etfw">6 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">A list of free courses, books, tutorials and cheat sheets for R <a href="https://t.co/kqOZvTMrIw">https://t.co/kqOZvTMrIw</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; One R Tip a Day (@RLangTip) <a href="https://twitter.com/RLangTip/status/1042820684085264384?ref_src=twsrc%5Etfw">20 september 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">📣 Newly updated…<br>📄 &quot;Data transformation w/ data.table cheat sheet&quot; by Erik Petrovski<a href="https://t.co/1Iw0HT0WJO">https://t.co/1Iw0HT0WJO</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/rdatatable?src=hash&amp;ref_src=twsrc%5Etfw">#rdatatable</a> <a href="https://t.co/RNaZ4vOFzG">pic.twitter.com/RNaZ4vOFzG</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1083725742595297280?ref_src=twsrc%5Etfw">11 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">A little Christmas present to myself 🎁<br>Learning Statistics with R has an internet home 🏠of its very own <a href="https://t.co/uwTlvx3rOK">https://t.co/uwTlvx3rOK</a></p>&mdash; Danielle Navarro (@djnavarro) <a href="https://twitter.com/djnavarro/status/1077703271936978944?ref_src=twsrc%5Etfw">25 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">TFW you learn about a package that does the *thing* that you couldn&#39;t articulate in a Google search. ✨😍✨<br><br>More gifs/info here: <a href="https://t.co/A2adsYFg26">https://t.co/A2adsYFg26</a> <a href="https://twitter.com/MilesMcBain?ref_src=twsrc%5Etfw">@MilesMcBain</a> <a href="https://t.co/WBIrUeJSq5">pic.twitter.com/WBIrUeJSq5</a></p>&mdash; Irene Steves (@i_steves) <a href="https://twitter.com/i_steves/status/1020127118208917504?ref_src=twsrc%5Etfw">20 juli 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Scholarnetwork: an R package that extract and visualize Google Scholar Collaboration Networks <a href="https://t.co/styuPbJQ7D">https://t.co/styuPbJQ7D</a> <a href="https://t.co/XArEF5WsEg">pic.twitter.com/XArEF5WsEg</a></p>&mdash; Not just Google Scholar&#39;s Digest (@GScholarDigest) <a href="https://twitter.com/GScholarDigest/status/959033161127743488?ref_src=twsrc%5Etfw">1 februari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">R and <a href="https://twitter.com/hashtag/Python?src=hash&amp;ref_src=twsrc%5Etfw">#Python</a> cheatsheets for <a href="https://twitter.com/hashtag/DataScientists?src=hash&amp;ref_src=twsrc%5Etfw">#DataScientists</a>: <a href="https://t.co/1uZN8EZcmz">https://t.co/1uZN8EZcmz</a> <a href="https://twitter.com/hashtag/abdsc?src=hash&amp;ref_src=twsrc%5Etfw">#abdsc</a> <a href="https://twitter.com/hashtag/BigData?src=hash&amp;ref_src=twsrc%5Etfw">#BigData</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://twitter.com/hashtag/Rstats?src=hash&amp;ref_src=twsrc%5Etfw">#Rstats</a> <a href="https://twitter.com/hashtag/MachineLearning?src=hash&amp;ref_src=twsrc%5Etfw">#MachineLearning</a> <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> <a href="https://t.co/EDHgXSA2Li">pic.twitter.com/EDHgXSA2Li</a></p>&mdash; Kirk Borne (@KirkDBorne) <a href="https://twitter.com/KirkDBorne/status/864200288709689348?ref_src=twsrc%5Etfw">15 mei 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Tools / Practices

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">How would you deal with legacy code? Read our new blog by Felipe Zapata: Dealing with Dragons and Monsters: Best Practices for Handling Legacy Code <a href="https://t.co/b8lQ7v8C7f">https://t.co/b8lQ7v8C7f</a> <a href="https://twitter.com/hashtag/Programming?src=hash&amp;ref_src=twsrc%5Etfw">#Programming</a> <a href="https://twitter.com/hashtag/LegacyCode?src=hash&amp;ref_src=twsrc%5Etfw">#LegacyCode</a> <a href="https://twitter.com/hashtag/SoftwareDevelopment?src=hash&amp;ref_src=twsrc%5Etfw">#SoftwareDevelopment</a> <a href="https://twitter.com/hashtag/eScience?src=hash&amp;ref_src=twsrc%5Etfw">#eScience</a> <a href="https://twitter.com/eScienceCenter?ref_src=twsrc%5Etfw">@eScienceCenter</a></p>&mdash; eScience Center (NL) (@eScienceCenter) <a href="https://twitter.com/eScienceCenter/status/1083951708294787079?ref_src=twsrc%5Etfw">12 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">My experience after having <a href="https://twitter.com/hashtag/peerreview?src=hash&amp;ref_src=twsrc%5Etfw">#peerreview</a>-ed ca. 100 manuscripts during the last eight years: Common reasons for recommending revision or rejection, the role of the abstract, and thoughts on the future of peer review. <a href="https://twitter.com/hashtag/openscience?src=hash&amp;ref_src=twsrc%5Etfw">#openscience</a> <a href="https://twitter.com/hashtag/publishing?src=hash&amp;ref_src=twsrc%5Etfw">#publishing</a> <a href="https://t.co/nHyxIQekmp">https://t.co/nHyxIQekmp</a> <a href="https://t.co/onCsXJHFem">pic.twitter.com/onCsXJHFem</a></p>&mdash; Stefan Pauliuk (@StefanPauliuk) <a href="https://twitter.com/StefanPauliuk/status/1076384894417338368?ref_src=twsrc%5Etfw">22 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">When I receive a speaking invite, my first q is: could I do a low-carbon video talk? Thanks to peoples&#39; willingness to give new-fangled tech a try, I now give about 3/4 of my talks this way! (thread, incl recommendations of platforms to use and avoid)</p>&mdash; Katharine Hayhoe (@KHayhoe) <a href="https://twitter.com/KHayhoe/status/1083071523433385985?ref_src=twsrc%5Etfw">9 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Getting reproducible - A toolkit for data transparency takes shape <a href="https://twitter.com/nature?ref_src=twsrc%5Etfw">@nature</a> <a href="https://t.co/mue80kDkif">https://t.co/mue80kDkif</a> <a href="https://t.co/kJaUuvH0PB">pic.twitter.com/kJaUuvH0PB</a></p>&mdash; 𝐆𝐈𝐎 𝐑𝐀𝐏𝐀𝐂𝐂𝐈𝐔𝐎𝐋𝐎 (@giorapac) <a href="https://twitter.com/giorapac/status/1031580017644298240?ref_src=twsrc%5Etfw">20 augustus 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">With a blog post containing some reflections on what I have learned during the last two years in Freiburg I enter the Christmas break.<br>See you all next year!<a href="https://t.co/fogky2tLcI">https://t.co/fogky2tLcI</a></p>&mdash; Stefan Pauliuk (@StefanPauliuk) <a href="https://twitter.com/StefanPauliuk/status/944173192675057664?ref_src=twsrc%5Etfw">22 december 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Guest post on the science of science communication: How <a href="https://twitter.com/IPCC_CH?ref_src=twsrc%5Etfw">@IPCC_CH</a> graphics could be made more accessible <a href="https://t.co/jzaSK3KTbn">https://t.co/jzaSK3KTbn</a> <a href="https://twitter.com/CarbonBrief?ref_src=twsrc%5Etfw">@CarbonBrief</a></p>&mdash; Heleen van Soest (@Hel1vs) <a href="https://twitter.com/Hel1vs/status/921458170622554112?ref_src=twsrc%5Etfw">20 oktober 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Just published a paper on factors affecting a university&#39;s citation and collaboration scores (free access)<a href="https://t.co/eTJNLhM5aA">https://t.co/eTJNLhM5aA</a></p>&mdash; Koen Frenken (@KFrenken) <a href="https://twitter.com/KFrenken/status/913826021400567811?ref_src=twsrc%5Etfw">29 september 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Writing / comms

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New Research |  &quot;Writing is underappreciated in science&quot; - Imagine how much extra impact peer-reviewed papers could have if they were written with the reader in mind |  <a href="https://twitter.com/Zoe_Doubleday?ref_src=twsrc%5Etfw">@Zoe_Doubleday</a> <a href="https://twitter.com/UniofAdelaide?ref_src=twsrc%5Etfw">@UniofAdelaide</a> <a href="https://t.co/zv3q9y6mVy">https://t.co/zv3q9y6mVy</a> <a href="https://t.co/ApSpQvmeAJ">pic.twitter.com/ApSpQvmeAJ</a></p>&mdash; Roz Pidcock (@RozPidcock) <a href="https://twitter.com/RozPidcock/status/1082960433512939520?ref_src=twsrc%5Etfw">9 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Now in NatureClimate - Comment: Reassessing emotion in climate change communication <a href="https://t.co/KHAbHyChlu">https://t.co/KHAbHyChlu</a></p>&mdash; NatureClimate (@NatureClimate) <a href="https://twitter.com/NatureClimate/status/939273389172281344?ref_src=twsrc%5Etfw">8 december 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">From science to policy: how to improve the dialogue? via <a href="https://twitter.com/CICERO_klima?ref_src=twsrc%5Etfw">@CICERO_klima</a> <a href="https://twitter.com/hashtag/scitopol?src=hash&amp;ref_src=twsrc%5Etfw">#scitopol</a> <a href="http://t.co/OCMEWb4US0">http://t.co/OCMEWb4US0</a></p>&mdash; IIASA (@IIASAVienna) <a href="https://twitter.com/IIASAVienna/status/648411447811293184?ref_src=twsrc%5Etfw">28 september 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">New Iyengar Massey review essay in PNAS on &quot;Scientific communication in a post-truth society&quot; <a href="https://t.co/mVkOBBjnb4">https://t.co/mVkOBBjnb4</a> <a href="https://t.co/zccY0sM3CR">pic.twitter.com/zccY0sM3CR</a></p>&mdash; Brendan Nyhan (@BrendanNyhan) <a href="https://twitter.com/BrendanNyhan/status/1068846504876695552?ref_src=twsrc%5Etfw">1 december 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Over the past year we&#39;ve been talking to experts from different backgrounds, about how they communicate climate change and the ways we can do this effectively. More detail and our shiny new report available here:<a href="https://t.co/gagrAS0s7P">https://t.co/gagrAS0s7P</a></p>&mdash; StuartCapstick (@StuartBCapstick) <a href="https://twitter.com/StuartBCapstick/status/1067365927598071808?ref_src=twsrc%5Etfw">27 november 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## (Data) Visualisation

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">🎨 one palette pkg to rule them all...<br>&quot;paletteer: Collection of most color palettes in a single R 📦&quot; 👨
🎨 <a href="https://twitter.com/Emil_Hvitfeldt?ref_src=twsrc%5Etfw">@Emil_Hvitfeldt</a> <a href="https://t.co/7kKSyohQN4">https://t.co/7kKSyohQN4</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a><br>/* w/ more palettes than a tweet can contain */ <a href="https://t.co/Qt1PlfDDpn">pic.twitter.com/Qt1PlfDDpn</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1081913803976134656?ref_src=twsrc%5Etfw">6 januari 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Blog 3, from seed to cereal bowl—we visualised soy trade with <a href="https://twitter.com/SEIresearch?ref_src=twsrc%5Etfw">@SEIresearch</a> using a first-of-its-kind sankey diagram <a href="https://t.co/AyTLCeLK8K">https://t.co/AyTLCeLK8K</a> <a href="https://t.co/JagtBysWEp">pic.twitter.com/JagtBysWEp</a></p>&mdash; Vizzuality (@Vizzuality) <a href="https://twitter.com/Vizzuality/status/814486563589603328?ref_src=twsrc%5Etfw">29 december 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Interactive map: 50,000 wind turbines generate 1/3 of America’s green energy <a href="https://t.co/5nGJGvBsxn">https://t.co/5nGJGvBsxn</a> <a href="https://twitter.com/EcoWatch?ref_src=twsrc%5Etfw">@EcoWatch</a> <a href="https://t.co/xl8lYZM8ET">pic.twitter.com/xl8lYZM8ET</a></p>&mdash; GCCA (@tcktcktck) <a href="https://twitter.com/tcktcktck/status/674619675246854145?ref_src=twsrc%5Etfw">9 december 2015</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">More than two years ago, I created the same chart with 24 different data vis tools. I just published an article (re)visiting nine of them, among others <a href="https://twitter.com/infogram?ref_src=twsrc%5Etfw">@infogram</a> <a href="https://twitter.com/f_l_o_u_r_i_s_h?ref_src=twsrc%5Etfw">@f_l_o_u_r_i_s_h</a> <a href="https://twitter.com/Datawrapper?ref_src=twsrc%5Etfw">@Datawrapper</a> <a href="https://twitter.com/plotlygraphs?ref_src=twsrc%5Etfw">@plotlygraphs</a> <a href="https://twitter.com/rawgraphs?ref_src=twsrc%5Etfw">@rawgraphs</a> &amp; <a href="https://twitter.com/tableau?ref_src=twsrc%5Etfw">@tableau</a>: <a href="https://t.co/t85vRbezqT">https://t.co/t85vRbezqT</a></p>&mdash; Lisa Charlotte Rost (@lisacrost) <a href="https://twitter.com/lisacrost/status/1052991963996323840?ref_src=twsrc%5Etfw">18 oktober 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">r2d3: R Interface to D3 Visualizations <a href="https://t.co/RKRuWYDniL">https://t.co/RKRuWYDniL</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/D3?src=hash&amp;ref_src=twsrc%5Etfw">#D3</a> <a href="https://t.co/5MlJbxKo6i">pic.twitter.com/5MlJbxKo6i</a></p>&mdash; RStudio (@rstudio) <a href="https://twitter.com/rstudio/status/1048234057824423937?ref_src=twsrc%5Etfw">5 oktober 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Text mining

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">What is the future alternative transport fuel? Every year a different answer:<a href="https://t.co/KU2Fgys56s">https://t.co/KU2Fgys56s</a> <a href="https://twitter.com/hashtag/Verkehrswende?src=hash&amp;ref_src=twsrc%5Etfw">#Verkehrswende</a> <a href="https://t.co/7wlSZP34mN">pic.twitter.com/7wlSZP34mN</a></p>&mdash; Brigitte Knopf (@BrigitteKnopf) <a href="https://twitter.com/BrigitteKnopf/status/701983348428816384?ref_src=twsrc%5Etfw">23 februari 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Interesting comparative analysis of how <a href="https://twitter.com/nature?ref_src=twsrc%5Etfw">@nature</a> and <a href="https://twitter.com/sciencemagazine?ref_src=twsrc%5Etfw">@sciencemagazine</a> have framed <a href="https://twitter.com/hashtag/climatechange?src=hash&amp;ref_src=twsrc%5Etfw">#climatechange</a> in editorials over the last 5 decades <a href="https://t.co/KjwDZWJZlB">https://t.co/KjwDZWJZlB</a></p>&mdash; Jenn Richler (@JennRichler) <a href="https://twitter.com/JennRichler/status/1001128985206624257?ref_src=twsrc%5Etfw">28 mei 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Data repositories

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Announcing the <a href="https://twitter.com/hashtag/rollout?src=hash&amp;ref_src=twsrc%5Etfw">#rollout</a> of the <a href="https://twitter.com/hashtag/IndustrialEcology?src=hash&amp;ref_src=twsrc%5Etfw">#IndustrialEcology</a> Freiburg <a href="https://twitter.com/hashtag/Database?src=hash&amp;ref_src=twsrc%5Etfw">#Database</a>: We will in the future publish our research results under a creative commons license! The dataset on the global <a href="https://twitter.com/hashtag/steel?src=hash&amp;ref_src=twsrc%5Etfw">#steel</a> cycle 1900-2008 for 146 countries marks the beginning. <a href="https://twitter.com/hashtag/openscience?src=hash&amp;ref_src=twsrc%5Etfw">#openscience</a><a href="https://t.co/0YCgOMhg08">https://t.co/0YCgOMhg08</a> <a href="https://t.co/vXQIY8Fr0j">pic.twitter.com/vXQIY8Fr0j</a></p>&mdash; Stefan Pauliuk (@StefanPauliuk) <a href="https://twitter.com/StefanPauliuk/status/933385504200056832?ref_src=twsrc%5Etfw">22 november 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">These 164 countries all have climate change laws<a href="https://t.co/5yPj4KoLUC">https://t.co/5yPj4KoLUC</a> <a href="https://t.co/j8gwjuEiF9">pic.twitter.com/j8gwjuEiF9</a></p>&mdash; Simon Evans (@DrSimEvans) <a href="https://twitter.com/DrSimEvans/status/862940642246348800?ref_src=twsrc%5Etfw">12 mei 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Age structure of <a href="https://twitter.com/hashtag/coal?src=hash&amp;ref_src=twsrc%5Etfw">#coal</a> power plants in EU countries. <br>From <a href="https://twitter.com/CA_Latest?ref_src=twsrc%5Etfw">@CA_Latest</a> report <a href="https://t.co/8kars52hfZ">https://t.co/8kars52hfZ</a> <a href="https://twitter.com/hashtag/EU2030?src=hash&amp;ref_src=twsrc%5Etfw">#EU2030</a> <a href="https://t.co/jaTuf5o8mM">pic.twitter.com/jaTuf5o8mM</a></p>&mdash; Oliver Geden (@Oliver_Geden) <a href="https://twitter.com/Oliver_Geden/status/835494922480418816?ref_src=twsrc%5Etfw">25 februari 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">I very much look forward to using Google Dataset Search to look for new <a href="https://twitter.com/hashtag/energy?src=hash&amp;ref_src=twsrc%5Etfw">#energy</a> <a href="https://twitter.com/hashtag/datasets?src=hash&amp;ref_src=twsrc%5Etfw">#datasets</a>. What a great idea!! <a href="https://twitter.com/hashtag/Energytwitter?src=hash&amp;ref_src=twsrc%5Etfw">#Energytwitter</a> colleagues,have you noticed? <a href="https://t.co/8VqGg9faYx">https://t.co/8VqGg9faYx</a> and <a href="https://t.co/7nA3HSYBYA">https://t.co/7nA3HSYBYA</a></p>&mdash; Evelina Trutnevyte (@etrutnevyte) <a href="https://twitter.com/etrutnevyte/status/1039166529542270977?ref_src=twsrc%5Etfw">10 september 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">For all number crunchers: Our annual compilation of German energy &amp; emissions data of German <a href="https://twitter.com/Umweltbundesamt?ref_src=twsrc%5Etfw">@Umweltbundesamt</a> for fuels &amp; sectors in different sector boundaries is now available for 1990 to 2016, the report in in German only but XLS data are available too: <a href="https://t.co/ClXgDvUvla">https://t.co/ClXgDvUvla</a></p>&mdash; Felix Chr. Matthes (@felixmatthes) <a href="https://twitter.com/felixmatthes/status/1020338304628285443?ref_src=twsrc%5Etfw">20 juli 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">To a low-carbon future we go. Now, with satellite data, researchers can access a database of power plants to reduce carbon emissions and enable <a href="https://twitter.com/hashtag/ML?src=hash&amp;ref_src=twsrc%5Etfw">#ML</a> for insights. <a href="https://t.co/jWh4Tlp7yp">https://t.co/jWh4Tlp7yp</a> <a href="https://t.co/oTARk52epB">pic.twitter.com/oTARk52epB</a></p>&mdash; Google Cloud (@googlecloud) <a href="https://twitter.com/googlecloud/status/987903577359290368?ref_src=twsrc%5Etfw">22 april 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Want to know more about the developments of the <a href="https://twitter.com/hashtag/MRIO?src=hash&amp;ref_src=twsrc%5Etfw">#MRIO</a> database <a href="https://twitter.com/hashtag/EXIOBASE?src=hash&amp;ref_src=twsrc%5Etfw">#EXIOBASE</a>? It consists of a time series of global economic trade and plenty of social and environmental indicators for <a href="https://twitter.com/hashtag/footprint?src=hash&amp;ref_src=twsrc%5Etfw">#footprint</a> analysis. Check out our new paper at <a href="https://twitter.com/JIndEcol?ref_src=twsrc%5Etfw">@JIndEcol</a> <a href="https://twitter.com/hashtag/industrialecology?src=hash&amp;ref_src=twsrc%5Etfw">#industrialecology</a> <a href="https://twitter.com/hashtag/ecologicaleconomics?src=hash&amp;ref_src=twsrc%5Etfw">#ecologicaleconomics</a> <a href="https://t.co/jvjF23iMI6">https://t.co/jvjF23iMI6</a></p>&mdash; Moana Simas (@moanasimas) <a href="https://twitter.com/moanasimas/status/952834291662139393?ref_src=twsrc%5Etfw">15 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Interesting <a href="https://twitter.com/hashtag/road?src=hash&amp;ref_src=twsrc%5Etfw">#road</a> and <a href="https://twitter.com/hashtag/railway?src=hash&amp;ref_src=twsrc%5Etfw">#railway</a> transport statistics for Europe <a href="https://t.co/0bYlH9Byjm">https://t.co/0bYlH9Byjm</a> via <a href="https://twitter.com/UNECE?ref_src=twsrc%5Etfw">@UNECE</a> <a href="https://t.co/ufXZFL4YDj">pic.twitter.com/ufXZFL4YDj</a></p>&mdash; CETMO (@f_CETMO) <a href="https://twitter.com/f_CETMO/status/951769977647915008?ref_src=twsrc%5Etfw">12 januari 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Who in the EU is best at reducing household carbon footprint? Great maps in this study: <a href="https://t.co/xhc1dNjLmb">https://t.co/xhc1dNjLmb</a> via <a href="https://twitter.com/IOPscience?ref_src=twsrc%5Etfw">@IOPscience</a></p>&mdash; Mark Stoll (@markrstoll) <a href="https://twitter.com/markrstoll/status/916687984606482432?ref_src=twsrc%5Etfw">7 oktober 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

